services:
  - type: web
    name: diet-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: diet-tracker-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false

  - type: web
    name: diet-tracker-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: API_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: diet-tracker-db
    plan: free