services:
  - type: web
    name: diet-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs # FastAPI's OpenAPI documentation path
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/diet_tracker.db
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: ${diet-tracker-frontend.RENDER_EXTERNAL_URL} # Frontend URL for CORS
    disk:
      name: diet-pdfs-and-db
      mountPath: /opt/render/project/src
      sizeGB: 1
    autoDeploy: true

  - type: web
    name: diet-tracker-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: API_URL
        value: ${diet-tracker-api.RENDER_EXTERNAL_URL} # API URL for frontend
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    dependencies:
      - name: diet-tracker-api


