services:
  - type: web
    name: diet-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: diet-tracker-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: ${RENDER_EXTERNAL_URL}  # This will automatically set to your frontend URL

  - type: web
    name: diet-tracker-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: API_URL
        value: ${diet-tracker-api.RENDER_EXTERNAL_URL}  # Automatically links to your API URL
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: diet-tracker-db
    databaseName: diet_tracker
    plan: free
    ipAllowList: []  # Allows all IPs