services:
  - type: web
    name: iem-vibe
    env: node
    plan: free
    buildCommand: cd diet-tracker-react && npm install && npm run build
    startCommand: cd diet-tracker-react && npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false
    autoDeploy: true
    rootDir: .


