// Food exchange data extracted from dietitian PDFs (Dr. Sheetal M Preventa Clinic)
// Each entry: { name, gramsPerExchange }
// For categories measured in grams/ml (jaggery, sugar, oil ghee, formulas, amino acids, soy milk)
// no exchange list is needed — amounts are tracked directly.

export const FOOD_EXCHANGES = {
  cereal: [
    { name: "Rice", gramsPerExchange: 7.3 },
    { name: "Rice flakes (Pohe)", gramsPerExchange: 8.7 },
    { name: "Rice puffed (Murmure)", gramsPerExchange: 8.7 },
    { name: "Rice flour", gramsPerExchange: 10.1 },
    { name: "Ragi (Nachni)", gramsPerExchange: 8.7 },
    { name: "Ragi flour", gramsPerExchange: 7.2 },
    { name: "Wheat flour (Atta)", gramsPerExchange: 6.5 },
    { name: "Wheat Semolina (Rava/Suji)", gramsPerExchange: 6.9 },
    { name: "Wheat vermicelli (Shevya)", gramsPerExchange: 10.2 },
    { name: "Millet (Bajri)", gramsPerExchange: 6.7 },
    { name: "Millet flour (Bajricha pith)", gramsPerExchange: 6.0 },
    { name: "Sorghum (Jowar)", gramsPerExchange: 7.8 },
    { name: "Sorghum flour (Jowar pith)", gramsPerExchange: 9.0 },
    { name: "Corn flour", gramsPerExchange: 10.0 },
    { name: "Samai (Sama/Vari)", gramsPerExchange: 6.5 },
    { name: "Amaranth seeds (Rajgira)", gramsPerExchange: 5.5 },
    { name: "Buckwheat (Kuttu)", gramsPerExchange: 5.2 },
    { name: "Oats", gramsPerExchange: 3.7 },
    { name: "Quinoa", gramsPerExchange: 5.9 },
    { name: "Varagu", gramsPerExchange: 7.1 },
    { name: "Barley pearled (Satu)", gramsPerExchange: 6.7 },
    { name: "Bread white (Pav)", gramsPerExchange: 10.4 },
    { name: "Bread wheat", gramsPerExchange: 13.5 },
    { name: "Pasta dry", gramsPerExchange: 6.0 },
    { name: "Pasta corn dry", gramsPerExchange: 9.3 },
    { name: "Rice noodles dry", gramsPerExchange: 10.1 },
    { name: "Macaroni dry", gramsPerExchange: 6.0 },
    { name: "Bulgur dry (Lapshi rava)", gramsPerExchange: 7.5 },
    { name: "Toast rusk", gramsPerExchange: 5.1 },
    { name: "Rice parboiled (Ukde tandul)", gramsPerExchange: 7.2 },
  ],

  "fresh fruit": [
    { name: "Apple big", gramsPerExchange: 147.8 },
    { name: "Apple small", gramsPerExchange: 110.5 },
    { name: "Banana (Kela)", gramsPerExchange: 20.2 },
    { name: "Mango (Amba)", gramsPerExchange: 35.7 },
    { name: "Mango Kesar", gramsPerExchange: 53.1 },
    { name: "Papaya (Papaya)", gramsPerExchange: 90.9 },
    { name: "Guava (Peru)", gramsPerExchange: 37.5 },
    { name: "Watermelon (Kalingad)", gramsPerExchange: 70.0 },
    { name: "Grapes seedless green", gramsPerExchange: 89.6 },
    { name: "Orange (Santre)", gramsPerExchange: 37.5 },
    { name: "Sweet lime (Mosambi)", gramsPerExchange: 114.1 },
    { name: "Pomegranate (Dalimb)", gramsPerExchange: 47.0 },
    { name: "Pineapple (Ananas)", gramsPerExchange: 70.9 },
    { name: "Pear (Naspati)", gramsPerExchange: 81.7 },
    { name: "Sapota / Chikoo", gramsPerExchange: 32.4 },
    { name: "Kiwi", gramsPerExchange: 26.3 },
    { name: "Strawberries", gramsPerExchange: 34.3 },
    { name: "Jamun (Black berry)", gramsPerExchange: 24.8 },
    { name: "Custard apple (Sitaphal)", gramsPerExchange: 19.1 },
    { name: "Gooseberry (Awala)", gramsPerExchange: 147.6 },
    { name: "Jackfruit (Phanas)", gramsPerExchange: 10.6 },
    { name: "Musk melon (Kharbuza)", gramsPerExchange: 92.5 },
    { name: "Litchi", gramsPerExchange: 25.0 },
    { name: "Plums (Alubukhaar)", gramsPerExchange: 64.6 },
    { name: "Peach (Pich)", gramsPerExchange: 32.1 },
    { name: "Figs fresh (Anjir)", gramsPerExchange: 13.8 },
  ],

  "dried fruit": [
    { name: "Raisins (Bedana/Kishmish)", gramsPerExchange: 18.1 },
    { name: "Dates (Khajur)", gramsPerExchange: 44.6 },
    { name: "Dates dry (Kharik)", gramsPerExchange: 19.1 },
    { name: "Apricots dried (Suke Jardalu)", gramsPerExchange: 20.5 },
    { name: "Figs dried (Suke Anjir)", gramsPerExchange: 12.3 },
    { name: "Plums dried (Suke Alubukhaar)", gramsPerExchange: 26.8 },
    { name: "Pears dried (Suke Naspati)", gramsPerExchange: 22.7 },
  ],

  legumes: [
    { name: "Green gram whole (Mung)", gramsPerExchange: 1.6 },
    { name: "Green gram dal (Mug dal)", gramsPerExchange: 1.6 },
    { name: "Green gram sprouts (Mod mung)", gramsPerExchange: 15.4 },
    { name: "Red gram dal (Tur dal)", gramsPerExchange: 2.1 },
    { name: "Red gram whole (Turi)", gramsPerExchange: 2.3 },
    { name: "Bengal gram dal (Chana dal)", gramsPerExchange: 2.3 },
    { name: "Chick peas (Chane)", gramsPerExchange: 2.3 },
    { name: "Chick peas boiled", gramsPerExchange: 5.4 },
    { name: "Chickpea flour (Besan)", gramsPerExchange: 8.0 },
    { name: "Lentil dal (Masur dal)", gramsPerExchange: 1.6 },
    { name: "Lentil whole (Masur)", gramsPerExchange: 1.8 },
    { name: "Black gram whole (Urad)", gramsPerExchange: 2.2 },
    { name: "Moth bean (Matki)", gramsPerExchange: 2.1 },
    { name: "Rajmah red", gramsPerExchange: 2.0 },
    { name: "Cowpea (Chavli)", gramsPerExchange: 2.0 },
    { name: "Field bean white (Pavte)", gramsPerExchange: 2.0 },
    { name: "Peas dry (Vatane)", gramsPerExchange: 2.1 },
    { name: "Horsegram (Kulith)", gramsPerExchange: 2.2 },
  ],

  "other vegetables": [
    { name: "Brinjal (Vangi)", gramsPerExchange: 29.4 },
    { name: "Bottle gourd (Dudhi)", gramsPerExchange: 58.5 },
    { name: "Bitter gourd (Karle)", gramsPerExchange: 20.0 },
    { name: "Ladies finger (Bhendi/Okra)", gramsPerExchange: 21.6 },
    { name: "Cauliflower (Phulavar)", gramsPerExchange: 16.0 },
    { name: "Capsicum green (Simla mirchi)", gramsPerExchange: 34.9 },
    { name: "Capsicum red", gramsPerExchange: 26.3 },
    { name: "Cucumber (Kakdi)", gramsPerExchange: 46.3 },
    { name: "French beans (Farsabi)", gramsPerExchange: 14.9 },
    { name: "Pumpkin (Bhopla/Lal bhopla)", gramsPerExchange: 39.0 },
    { name: "Tomato ripe (Tamato)", gramsPerExchange: 68.2 },
    { name: "Ridge gourd (Dodka/Shiral)", gramsPerExchange: 36.9 },
    { name: "Drumstick (Shevgyachya shenga)", gramsPerExchange: 15.2 },
    { name: "Cluster beans (Gavar)", gramsPerExchange: 14.2 },
    { name: "Snake gourd (Padval)", gramsPerExchange: 42.6 },
    { name: "Zucchini green", gramsPerExchange: 31.0 },
    { name: "Mushroom button", gramsPerExchange: 9.9 },
    { name: "Broccoli", gramsPerExchange: 16.0 },
    { name: "Tinda (Dhemse)", gramsPerExchange: 33.9 },
    { name: "Ash gourd (Kohla/Petha)", gramsPerExchange: 49.5 },
    { name: "Peas fresh (Matar)", gramsPerExchange: 6.5 },
    { name: "Raw papaya (Kachchi papai)", gramsPerExchange: 126.6 },
    { name: "Raw mango (Kairi)", gramsPerExchange: 50.1 },
    { name: "Parwar (Parval)", gramsPerExchange: 24.0 },
    { name: "Tondli (Kovai)", gramsPerExchange: 29.0 },
    { name: "Spinach (Palak)", gramsPerExchange: 16.0 },
    { name: "Cabbage (Kobi)", gramsPerExchange: 47.6 },
    { name: "Fenugreek leaves (Methi)", gramsPerExchange: 8.7 },
    { name: "Coriander leaves (Kothimbir)", gramsPerExchange: 8.8 },
    { name: "Colocasia leaves (Aluchi pane)", gramsPerExchange: 12.6 },
    { name: "Amaranth leaves (Math bhaji)", gramsPerExchange: 12.1 },
    { name: "Curry leaves (Kadhipatta)", gramsPerExchange: 6.9 },
    { name: "Dill leaves (Shepu)", gramsPerExchange: 13.0 },
  ],

  "root vegetables": [
    { name: "Potato (Batata)", gramsPerExchange: 30.3 },
    { name: "Potato boiled", gramsPerExchange: 20.0 },
    { name: "Carrot (Gajar)", gramsPerExchange: 46.0 },
    { name: "Beet root (Bit)", gramsPerExchange: 18.3 },
    { name: "Onion big (Kanda)", gramsPerExchange: 48.5 },
    { name: "Onion small (Shallots)", gramsPerExchange: 28.0 },
    { name: "Sweet potato (Ratale)", gramsPerExchange: 27.0 },
    { name: "Colocasia (Alkudi/Arabi)", gramsPerExchange: 11.3 },
    { name: "Radish white (Mula)", gramsPerExchange: 46.6 },
    { name: "Plantain green (Kachche kele)", gramsPerExchange: 30.8 },
    { name: "Yam (Suran)", gramsPerExchange: 19.9 },
    { name: "Tapioca (Simla batata)", gramsPerExchange: 41.1 },
    { name: "Lotus root (Kamal kakdi)", gramsPerExchange: 22.6 },
    { name: "Casava", gramsPerExchange: 57.1 },
  ],

  "free group": [
    { name: "Sago / Arrowroot (Sabudana)", gramsPerExchange: 14 },
    { name: "Corn Starch (Cornflour)", gramsPerExchange: 13 },
    { name: "Wheat Starch", gramsPerExchange: 14 },
    { name: "Maize Corn Starch", gramsPerExchange: 14 },
    { name: "Mixed Fruit Jam", gramsPerExchange: 18 },
    { name: "Molasses", gramsPerExchange: 17 },
    { name: "Custard Powder", gramsPerExchange: 13 },
    { name: "Corn Syrup (Light)", gramsPerExchange: 18 },
    { name: "Rice Milk", gramsPerExchange: 105, unit: "ml" },
    { name: "Aam Papad", gramsPerExchange: 16 },
    { name: "Gulkand", gramsPerExchange: 18 },
    { name: "Ice cream (Creambell)", gramsPerExchange: 41 },
  ],
};
