// Food exchange data extracted from dietitian PDFs (Dr. Sheetal M Preventa Clinic)
// Each entry: { name, gramsPerExchange }
// For categories measured in ml, unit: "ml" is specified.

export const FOOD_EXCHANGES = {
  cereal: [
    { name: "Rice", marathi: "तांदूळ", gramsPerExchange: 7.3 },
    { name: "Rice flakes (Pohe)", marathi: "पोहे", gramsPerExchange: 8.7 },
    { name: "Rice puffed (Murmure)", marathi: "मुरमुरे", gramsPerExchange: 8.7 },
    { name: "Rice flour", marathi: "तांदळाचे पीठ", gramsPerExchange: 10.1 },
    { name: "Ragi (Nachni)", marathi: "नाचणी", gramsPerExchange: 8.7 },
    { name: "Ragi flour", marathi: "नाचणीचे पीठ", gramsPerExchange: 7.2 },
    { name: "Wheat flour (Atta)", marathi: "गव्हाचे पीठ (आटा)", gramsPerExchange: 6.5 },
    { name: "Wheat Semolina (Rava/Suji)", marathi: "रवा / सुजी", gramsPerExchange: 6.9 },
    { name: "Wheat vermicelli (Shevya)", marathi: "शेवया", gramsPerExchange: 10.2 },
    { name: "Millet (Bajri)", marathi: "बाजरी", gramsPerExchange: 6.7 },
    { name: "Millet flour (Bajricha pith)", marathi: "बाजरीचे पीठ", gramsPerExchange: 6.0 },
    { name: "Sorghum (Jowar)", marathi: "ज्वारी", gramsPerExchange: 7.8 },
    { name: "Sorghum flour (Jowar pith)", marathi: "ज्वारीचे पीठ", gramsPerExchange: 9.0 },
    { name: "Corn flour", marathi: "मक्याचे पीठ", gramsPerExchange: 10.0 },
    { name: "Samai (Sama/Vari)", marathi: "वरी / साठे", gramsPerExchange: 6.5 },
    { name: "Amaranth seeds (Rajgira)", marathi: "राजगिरा", gramsPerExchange: 5.5 },
    { name: "Buckwheat (Kuttu)", marathi: "कुट्टू", gramsPerExchange: 5.2 },
    { name: "Oats", marathi: "ओट्स", gramsPerExchange: 3.7 },
    { name: "Quinoa", marathi: "क्विनोआ", gramsPerExchange: 5.9 },
    { name: "Varagu", marathi: "वरगू", gramsPerExchange: 7.1 },
    { name: "Barley pearled (Satu)", marathi: "जव / सातू", gramsPerExchange: 6.7 },
    { name: "Bread white (Pav)", marathi: "पाव", gramsPerExchange: 10.4 },
    { name: "Bread wheat", marathi: "गव्हाचा ब्रेड", gramsPerExchange: 13.5 },
    { name: "Pasta dry", gramsPerExchange: 6.0 },
    { name: "Pasta corn dry", gramsPerExchange: 9.3 },
    { name: "Rice noodles dry", marathi: "तांदळाच्या नूडल्स", gramsPerExchange: 10.1 },
    { name: "Macaroni dry", gramsPerExchange: 6.0 },
    { name: "Bulgur dry (Lapshi rava)", marathi: "लापशी रवा", gramsPerExchange: 7.5 },
    { name: "Toast rusk", gramsPerExchange: 5.1 },
    { name: "Rice parboiled (Ukde tandul)", marathi: "उकडे तांदूळ", gramsPerExchange: 7.2 },
    { name: "Amaranth seeds pale brown (Rajgira)", marathi: "राजगिरा", gramsPerExchange: 6.1 },
    { name: "Bread crumbs", gramsPerExchange: 5.8 },
    { name: "Bread multi-grain", gramsPerExchange: 8.8 },
    { name: "Bread pita whole wheat", gramsPerExchange: 7.9 },
    { name: "Bread pita white", gramsPerExchange: 8.9 },
    { name: "Bread stick", gramsPerExchange: 6.8 },
    { name: "Brown rice flakes", marathi: "तपकिरी तांदळाचे पोहे", gramsPerExchange: 9.3 },
    { name: "Couscous dry", gramsPerExchange: 6.4 },
    { name: "Couscous cooked", gramsPerExchange: 21.6 },
    { name: "Ice cream cones (wafer)", gramsPerExchange: 10.3 },
    { name: "Macaroni cooked", gramsPerExchange: 13.4 },
    { name: "Macaroni whole wheat dry", gramsPerExchange: 5.5 },
    { name: "Macaroni whole wheat cooked", gramsPerExchange: 15.2 },
    { name: "Maize dry", marathi: "मका", gramsPerExchange: 7.4 },
    { name: "Millet cooked (Bajri)", marathi: "शिजवलेली बाजरी", gramsPerExchange: 19.0 },
    { name: "Noodles Chinese chow Mein", gramsPerExchange: 9.9 },
    { name: "Noodles rice cooked", marathi: "शिजवलेल्या तांदळाच्या नूडल्स", gramsPerExchange: 33.7 },
    { name: "Oats bran", marathi: "ओट्स कोंडा", gramsPerExchange: 3.6 },
    { name: "Oats bran cooked", marathi: "शिजवलेला ओट्स कोंडा", gramsPerExchange: 21.2 },
    { name: "Pasta cooked", gramsPerExchange: 13.4 },
    { name: "Pasta corn cooked", gramsPerExchange: 26.3 },
    { name: "Pasta whole wheat cooked", gramsPerExchange: 13.5 },
    { name: "Quinoa cooked", marathi: "शिजवलेला क्विनोआ", gramsPerExchange: 18.9 },
    { name: "Rice brown raw", marathi: "तपकिरी तांदूळ (कच्चा)", gramsPerExchange: 5.7 },
    { name: "Rice brown cooked", marathi: "शिजवलेला तपकिरी तांदूळ", gramsPerExchange: 23.2 },
    { name: "Rice flour brown", marathi: "तपकिरी तांदळाचे पीठ", gramsPerExchange: 8.3 },
    { name: "Rice long grain", marathi: "लांब दाण्याचा तांदूळ", gramsPerExchange: 8.0 },
    { name: "Rice medium grain", marathi: "मध्यम दाण्याचा तांदूळ", gramsPerExchange: 8.7 },
    { name: "Rice parboiled cooked", marathi: "शिजवलेले उकडे तांदूळ", gramsPerExchange: 18.9 },
    { name: "Rice short grain", marathi: "आखूड दाण्याचा तांदूळ", gramsPerExchange: 8.8 },
    { name: "Spaghetti dry", gramsPerExchange: 6.0 },
    { name: "Spaghetti cooked", gramsPerExchange: 13.4 },
    { name: "Spaghetti whole wheat dry", gramsPerExchange: 5.5 },
    { name: "Spaghetti whole wheat cooked", gramsPerExchange: 15.2 },
    { name: "Wheat bulgur cooked (Lapshi rava)", marathi: "शिजवलेला लापशी रवा", gramsPerExchange: 25.2 },
    { name: "Wheat flour refined (Maida)", marathi: "मैदा", gramsPerExchange: 8.4 },
    { name: "Wheat vermicelli roasted", marathi: "भाजलेल्या शेवया", gramsPerExchange: 9.1 },
    { name: "Wheat whole grain (Gehun)", marathi: "गहू", gramsPerExchange: 6.5 },
    { name: "Wild rice raw", gramsPerExchange: 4.1 },
    { name: "Wild rice cooked", gramsPerExchange: 15.1 },
  ],

  "fresh fruit": [
    { name: "Apple big", marathi: "सफरचंद", gramsPerExchange: 147.8 },
    { name: "Apple small", marathi: "सफरचंद", gramsPerExchange: 110.5 },
    { name: "Banana (Kela)", marathi: "केळ", gramsPerExchange: 20.2 },
    { name: "Mango (Amba)", marathi: "आंबा", gramsPerExchange: 35.7 },
    { name: "Mango Kesar", marathi: "केसर आंबा", gramsPerExchange: 53.1 },
    { name: "Papaya (Papaya)", marathi: "पपई", gramsPerExchange: 90.9 },
    { name: "Guava (Peru)", marathi: "पेरू", gramsPerExchange: 37.5 },
    { name: "Watermelon (Kalingad)", marathi: "कलिंगड", gramsPerExchange: 70.0 },
    { name: "Grapes seedless green", marathi: "द्राक्षे (हिरवी)", gramsPerExchange: 89.6 },
    { name: "Orange (Santre)", marathi: "संत्रे", gramsPerExchange: 37.5 },
    { name: "Sweet lime (Mosambi)", marathi: "मोसंबी", gramsPerExchange: 114.1 },
    { name: "Pomegranate (Dalimb)", marathi: "डाळिंब", gramsPerExchange: 47.0 },
    { name: "Pineapple (Ananas)", marathi: "अननस", gramsPerExchange: 70.9 },
    { name: "Pear (Naspati)", marathi: "नासपाती", gramsPerExchange: 81.7 },
    { name: "Sapota / Chikoo", marathi: "चिकू", gramsPerExchange: 32.4 },
    { name: "Kiwi", marathi: "किवी", gramsPerExchange: 26.3 },
    { name: "Strawberries", marathi: "स्ट्रॉबेरी", gramsPerExchange: 34.3 },
    { name: "Jamun (Black berry)", marathi: "जांभूळ", gramsPerExchange: 24.8 },
    { name: "Custard apple (Sitaphal)", marathi: "सीताफळ", gramsPerExchange: 19.1 },
    { name: "Gooseberry (Awala)", marathi: "आवळा", gramsPerExchange: 147.6 },
    { name: "Jackfruit (Phanas)", marathi: "फणस", gramsPerExchange: 10.6 },
    { name: "Musk melon (Kharbuza)", marathi: "खरबूज", gramsPerExchange: 92.5 },
    { name: "Litchi", marathi: "लीची", gramsPerExchange: 25.0 },
    { name: "Plums (Alubukhaar)", marathi: "आलूबुखार", gramsPerExchange: 64.6 },
    { name: "Peach (Pich)", marathi: "पीच", gramsPerExchange: 32.1 },
    { name: "Figs fresh (Anjir)", marathi: "अंजीर", gramsPerExchange: 13.8 },
    { name: "Apple green", marathi: "हिरवे सफरचंद", gramsPerExchange: 89.1 },
    { name: "Apple sauce", marathi: "सफरचंद सॉस", gramsPerExchange: 187.5 },
    { name: "Apple sauce unsweetened", marathi: "सफरचंद सॉस (साखर नाही)", gramsPerExchange: 187.5 },
    { name: "Apple Kashmir", marathi: "काश्मिरी सफरचंद", gramsPerExchange: 132.9 },
    { name: "Apple golden", marathi: "गोल्डन सफरचंद", gramsPerExchange: 115.4 },
    { name: "Apple red with skin", marathi: "लाल सफरचंद (सालासकट)", gramsPerExchange: 125.0 },
    { name: "Apples without skin", marathi: "सफरचंद (सालाशिवाय)", gramsPerExchange: 125.0 },
    { name: "Apricots fresh (Jardalu)", marathi: "जर्दाळू", gramsPerExchange: 31.9 },
    { name: "Avocado (Makkhan phal)", marathi: "मक्खण फळ", gramsPerExchange: 11.4 },
    { name: "Bael fruit (Bel)", marathi: "बेल", gramsPerExchange: 12.4 },
    { name: "Banana ripe red", marathi: "लाल केळ", gramsPerExchange: 17.7 },
    { name: "Banana ripe robusta", marathi: "रोबस्टा केळ", gramsPerExchange: 20.16 },
    { name: "Banana ripe montham", marathi: "मोंथम केळ", gramsPerExchange: 20.62 },
    { name: "Banana ripe poovam", marathi: "पूवम केळ", gramsPerExchange: 16.5 },
    { name: "Blueberries", marathi: "ब्लूबेरी", gramsPerExchange: 48.4 },
    { name: "Cherimoya (Maruti phal)", marathi: "मारुती फळ", gramsPerExchange: 23.8 },
    { name: "Cherries sweet", marathi: "चेरी", gramsPerExchange: 21.1 },
    { name: "Crab apple (Jangali safarchand)", marathi: "जंगली सफरचंद", gramsPerExchange: 79.0 },
    { name: "Cranberries", marathi: "क्रॅनबेरी", gramsPerExchange: 33.3 },
    { name: "Currants black (Karwand)", marathi: "करवंद", gramsPerExchange: 19.4 },
    { name: "Elderberries", gramsPerExchange: 45.5 },
    { name: "Grapefruit pink", gramsPerExchange: 100.0 },
    { name: "Grapes seeded round black", marathi: "काळी द्राक्षे (बिया असलेली)", gramsPerExchange: 75.9 },
    { name: "Grapes seeded round green", marathi: "हिरवी द्राक्षे (बिया असलेली)", gramsPerExchange: 79.2 },
    { name: "Grapes seeded round red", marathi: "लाल द्राक्षे (बिया असलेली)", gramsPerExchange: 55.8 },
    { name: "Grapes seedless oval black", marathi: "काळी बिया नसलेली द्राक्षे", gramsPerExchange: 39.0 },
    { name: "Grapes seedless round black", marathi: "काळी गोल बिया नसलेली द्राक्षे", gramsPerExchange: 44.8 },
    { name: "Guava white", marathi: "पांढरा पेरू", gramsPerExchange: 31.9 },
    { name: "Jambu fruit ripe (Safed jaam)", marathi: "सफेद जाम", gramsPerExchange: 26.2 },
    { name: "Karonda fruit", marathi: "करवंद", gramsPerExchange: 28.2 },
    { name: "Lime (Nimbu)", marathi: "लिंबू", gramsPerExchange: 126.2 },
    { name: "Longan fresh", marathi: "लोंगन", gramsPerExchange: 25.9 },
    { name: "Mango banganapalli", marathi: "बंगणपल्ली आंबा", gramsPerExchange: 46.9 },
    { name: "Mango gulabkhas", marathi: "गुलाबखास आंबा", gramsPerExchange: 45.6 },
    { name: "Mango himsagar", marathi: "हिमसागर आंबा", gramsPerExchange: 67.0 },
    { name: "Mango neelam", marathi: "नीलम आंबा", gramsPerExchange: 35.1 },
    { name: "Mango paheri", marathi: "पहेरी आंबा", gramsPerExchange: 36.0 },
    { name: "Mango totapuri", marathi: "तोतापुरी आंबा", gramsPerExchange: 61.8 },
    { name: "Mangosteen", gramsPerExchange: 44.4 },
    { name: "Manila tamarind (Vilayati chinch)", marathi: "विलायती चिंच", gramsPerExchange: 8.6 },
    { name: "Musk melon orange flesh", marathi: "खरबूज (नारिंगी गर)", gramsPerExchange: 107.3 },
    { name: "Nectarines", gramsPerExchange: 115.4 },
    { name: "Orange pulp (Santre)", marathi: "संत्र्याचा गर", gramsPerExchange: 101.1 },
    { name: "Palm fruit tender (Tadgola)", marathi: "ताडगोळा", gramsPerExchange: 69.6 },
    { name: "Pears Asian", marathi: "आशियाई नासपाती", gramsPerExchange: 83.3 },
    { name: "Phalsa", marathi: "फालसा", gramsPerExchange: 15.7 },
    { name: "Pineapple chunks frozen", marathi: "अननसाचे तुकडे (गोठवलेले)", gramsPerExchange: 93.8 },
    { name: "Pummelo / Papanus", marathi: "पापनस", gramsPerExchange: 52.2 },
    { name: "Rambutan", gramsPerExchange: 46.2 },
    { name: "Soursop (Shul ramphal)", marathi: "शुल रामफळ", gramsPerExchange: 34.3 },
    { name: "Star fruit (Karambola)", marathi: "कमरख", gramsPerExchange: 45.1 },
    { name: "Tamarind pulp (Chinch)", marathi: "चिंच", gramsPerExchange: 12.8 },
    { name: "Tangerines mandarin oranges", marathi: "किन्नू / मँडरिन", gramsPerExchange: 71.4 },
    { name: "Watermelon dark green (sugar baby)", marathi: "कलिंगड (गडद हिरवे)", gramsPerExchange: 70.6 },
    { name: "Watermelon pale green", marathi: "कलिंगड (फिकट हिरवे)", gramsPerExchange: 69.9 },
    { name: "Wood apple (Kawath)", marathi: "कवठ", gramsPerExchange: 12.8 },
    { name: "Zizyphus (Bor)", marathi: "बोर", gramsPerExchange: 24.0 },
  ],

  "dried fruit": [
    { name: "Raisins (Bedana/Kishmish)", marathi: "बेदाणे / किशमिश", gramsPerExchange: 18.1 },
    { name: "Dates (Khajur)", marathi: "खजूर", gramsPerExchange: 44.6 },
    { name: "Dates dry (Kharik)", marathi: "खारीक", gramsPerExchange: 19.1 },
    { name: "Apricots dried (Suke Jardalu)", marathi: "सुके जर्दाळू", gramsPerExchange: 20.5 },
    { name: "Figs dried (Suke Anjir)", marathi: "सुके अंजीर", gramsPerExchange: 12.3 },
    { name: "Plums dried (Suke Alubukhaar)", marathi: "सुके आलूबुखार", gramsPerExchange: 26.8 },
    { name: "Pears dried (Suke Naspati)", marathi: "सुकी नासपाती", gramsPerExchange: 22.7 },
    { name: "Apricot processed", marathi: "जर्दाळू (प्रक्रिया केलेले)", gramsPerExchange: 48.1 },
    { name: "Apricots dried stewed unsweetened", marathi: "सुके जर्दाळू (साखर नाही)", gramsPerExchange: 53.6 },
    { name: "Apricots dried stewed with sugar", marathi: "सुके जर्दाळू (साखरेसह)", gramsPerExchange: 34.9 },
    { name: "Dates dry pale brown", marathi: "फिकट तपकिरी खारीक", gramsPerExchange: 21.5 },
    { name: "Figs dried stewed", marathi: "सुके अंजीर (शिजवलेले)", gramsPerExchange: 28.3 },
    { name: "Goji berries dried", marathi: "सुके गोजी बेरी", gramsPerExchange: 4.7 },
    { name: "Peach dried uncooked", marathi: "सुके पीच", gramsPerExchange: 7.6 },
    { name: "Peach dried stewed with sugar", marathi: "सुके पीच (साखरेसह)", gramsPerExchange: 25.9 },
    { name: "Peach dried stewed without sugar", marathi: "सुके पीच (साखर नाही)", gramsPerExchange: 23.8 },
    { name: "Pears dried stewed with sugar", marathi: "सुकी नासपाती (साखरेसह)", gramsPerExchange: 50.0 },
    { name: "Pears dried stewed without sugar", marathi: "सुकी नासपाती (साखर नाही)", gramsPerExchange: 46.9 },
    { name: "Raisins black dried (Manuka)", marathi: "मनुका", gramsPerExchange: 20.3 },
    { name: "Raisins golden (Kishmish)", marathi: "किशमिश (सोनेरी)", gramsPerExchange: 19.1 },
  ],

  legumes: [
    { name: "Green gram whole (Mung)", marathi: "मूग (साबूत)", gramsPerExchange: 1.6 },
    { name: "Green gram dal (Mug dal)", marathi: "मुगडाळ", gramsPerExchange: 1.6 },
    { name: "Green gram sprouts (Mod mung)", marathi: "मोड आलेले मूग", gramsPerExchange: 15.4 },
    { name: "Red gram dal (Tur dal)", marathi: "तूरडाळ", gramsPerExchange: 2.1 },
    { name: "Red gram whole (Turi)", marathi: "तूर (साबूत)", gramsPerExchange: 2.3 },
    { name: "Bengal gram dal (Chana dal)", marathi: "चनाडाळ", gramsPerExchange: 2.3 },
    { name: "Chick peas (Chane)", marathi: "चणे", gramsPerExchange: 2.3 },
    { name: "Chick peas boiled", marathi: "शिजवलेले चणे", gramsPerExchange: 5.4 },
    { name: "Chickpea flour (Besan)", marathi: "बेसन", gramsPerExchange: 8.0 },
    { name: "Lentil dal (Masur dal)", marathi: "मसूरडाळ", gramsPerExchange: 1.6 },
    { name: "Lentil whole (Masur)", marathi: "मसूर (साबूत)", gramsPerExchange: 1.8 },
    { name: "Black gram whole (Urad)", marathi: "उडीद (साबूत)", gramsPerExchange: 2.2 },
    { name: "Moth bean (Matki)", marathi: "मटकी", gramsPerExchange: 2.1 },
    { name: "Rajmah red", marathi: "लाल राजमा", gramsPerExchange: 2.0 },
    { name: "Cowpea (Chavli)", marathi: "चवळी", gramsPerExchange: 2.0 },
    { name: "Field bean white (Pavte)", marathi: "पावटे (पांढरे)", gramsPerExchange: 2.0 },
    { name: "Peas dry (Vatane)", marathi: "वाटाणे (सुके)", gramsPerExchange: 2.1 },
    { name: "Horsegram (Kulith)", marathi: "कुळीथ", gramsPerExchange: 2.2 },
    { name: "Adzuki beans", gramsPerExchange: 2.0 },
    { name: "Adzuki beans boiled", gramsPerExchange: 5.2 },
    { name: "Beans kidney sprouted", marathi: "मोड आलेले राजमा", gramsPerExchange: 9.3 },
    { name: "Beans kidney sprouted cooked", marathi: "शिजवलेले मोड आलेले राजमा", gramsPerExchange: 8.1 },
    { name: "Beans pinto sprouted", gramsPerExchange: 7.4 },
    { name: "Beans pinto sprouted boiled", gramsPerExchange: 21.1 },
    { name: "Beans white", gramsPerExchange: 1.6 },
    { name: "Beans white boiled", gramsPerExchange: 3.9 },
    { name: "Beans white small", gramsPerExchange: 1.8 },
    { name: "Beans white small boiled", gramsPerExchange: 4.3 },
    { name: "Beans yellow", gramsPerExchange: 1.7 },
    { name: "Beans yellow boiled", gramsPerExchange: 4.2 },
    { name: "Black beans", marathi: "काळे बीन्स", gramsPerExchange: 1.8 },
    { name: "Black beans boiled", marathi: "शिजवलेले काळे बीन्स", gramsPerExchange: 4.7 },
    { name: "Black gram dal (Urad dal)", marathi: "उडीद डाळ", gramsPerExchange: 1.9 },
    { name: "Cowpea brown", marathi: "तपकिरी चवळी", gramsPerExchange: 2.0 },
    { name: "Cowpea white", marathi: "पांढरी चवळी", gramsPerExchange: 1.8 },
    { name: "Cranberry beans (Chitriwale rajmah)", marathi: "चित्रीवाले राजमा", gramsPerExchange: 1.7 },
    { name: "Cranberry beans boiled", gramsPerExchange: 4.1 },
    { name: "Field bean black (Val kale)", marathi: "काळे वाल", gramsPerExchange: 1.9 },
    { name: "Field bean brown (Val kadwe)", marathi: "तपकिरी वाल", gramsPerExchange: 1.9 },
    { name: "French beans mature seeds", marathi: "फरसबी (पक्की बी)", gramsPerExchange: 2.0 },
    { name: "French beans mature seeds boiled", marathi: "शिजवलेली फरसबी बी", gramsPerExchange: 5.4 },
    { name: "Great northern beans", gramsPerExchange: 1.7 },
    { name: "Great northern beans boiled", gramsPerExchange: 4.6 },
    { name: "Green gram sprouts boiled", marathi: "शिजवलेले मोड आलेले मूग", gramsPerExchange: 20.6 },
    { name: "Lentil whole yellowish", marathi: "पिवळी मसूर (साबूत)", gramsPerExchange: 1.8 },
    { name: "Lentil sprouts", marathi: "मोड आलेली मसूर", gramsPerExchange: 5.0 },
    { name: "Lentil sprouts boiled", marathi: "शिजवलेली मोड आलेली मसूर", gramsPerExchange: 5.1 },
    { name: "Lupins seeds", gramsPerExchange: 1.3 },
    { name: "Lupins seeds boiled", gramsPerExchange: 3.1 },
    { name: "Navy beans", gramsPerExchange: 1.6 },
    { name: "Navy beans boiled", gramsPerExchange: 4.0 },
    { name: "Navy bean sprouts", gramsPerExchange: 6.3 },
    { name: "Navy bean sprouts boiled", gramsPerExchange: 5.5 },
    { name: "Peas green split", marathi: "हिरवे वाटाणे (विभागलेले)", gramsPerExchange: 1.7 },
    { name: "Peas mature sprouts", marathi: "मोड आलेले वाटाणे", gramsPerExchange: 9.1 },
    { name: "Peas mature sprouts boiled", marathi: "शिजवलेले मोड आलेले वाटाणे", gramsPerExchange: 7.0 },
    { name: "Pink beans", gramsPerExchange: 1.8 },
    { name: "Pink beans boiled", gramsPerExchange: 4.2 },
    { name: "Pinto beans", gramsPerExchange: 2.0 },
    { name: "Pinto beans boiled", gramsPerExchange: 3.9 },
    { name: "Rajmah black", marathi: "काळा राजमा", gramsPerExchange: 2.2 },
    { name: "Rajmah brown", marathi: "तपकिरी राजमा", gramsPerExchange: 2.0 },
    { name: "Ricebean (Math)", marathi: "मठ", gramsPerExchange: 1.9 },
    { name: "Soya bean brown", marathi: "सोयाबीन (तपकिरी)", gramsPerExchange: 1.1 },
    { name: "Soya bean white", marathi: "सोयाबीन (पांढरे)", gramsPerExchange: 1.0 },
    { name: "Soybean sprouts", marathi: "मोड आलेले सोयाबीन", gramsPerExchange: 3.2 },
    { name: "Soybean sprouts boiled", marathi: "शिजवलेले मोड आलेले सोयाबीन", gramsPerExchange: 5.0 },
    { name: "Yardlong beans seeds", marathi: "चवळीच्या शेंगांच्या बिया", gramsPerExchange: 1.7 },
    { name: "Yardlong beans seeds boiled", marathi: "शिजवलेल्या चवळीच्या बिया", gramsPerExchange: 5.1 },
  ],

  "other vegetables": [
    { name: "Brinjal (Vangi)", marathi: "वांगी", gramsPerExchange: 29.4 },
    { name: "Bottle gourd (Dudhi)", marathi: "दुधी भोपळा", gramsPerExchange: 58.5 },
    { name: "Bitter gourd (Karle)", marathi: "कारले", gramsPerExchange: 20.0 },
    { name: "Ladies finger (Bhendi/Okra)", marathi: "भेंडी", gramsPerExchange: 21.6 },
    { name: "Cauliflower (Phulavar)", marathi: "फुलकोबी", gramsPerExchange: 16.0 },
    { name: "Capsicum green (Simla mirchi)", marathi: "सिमला मिरची (हिरवी)", gramsPerExchange: 34.9 },
    { name: "Capsicum red", marathi: "सिमला मिरची (लाल)", gramsPerExchange: 26.3 },
    { name: "Cucumber (Kakdi)", marathi: "काकडी", gramsPerExchange: 46.3 },
    { name: "French beans (Farsabi)", marathi: "फरसबी", gramsPerExchange: 14.9 },
    { name: "Pumpkin (Bhopla/Lal bhopla)", marathi: "भोपळा", gramsPerExchange: 39.0 },
    { name: "Tomato ripe (Tamato)", marathi: "टोमॅटो", gramsPerExchange: 68.2 },
    { name: "Ridge gourd (Dodka/Shiral)", marathi: "दोडका / शिराळी", gramsPerExchange: 36.9 },
    { name: "Drumstick (Shevgyachya shenga)", marathi: "शेवग्याच्या शेंगा", gramsPerExchange: 15.2 },
    { name: "Cluster beans (Gavar)", marathi: "गवार", gramsPerExchange: 14.2 },
    { name: "Snake gourd (Padval)", marathi: "पडवळ", gramsPerExchange: 42.6 },
    { name: "Zucchini green", marathi: "झुकिनी (हिरवी)", gramsPerExchange: 31.0 },
    { name: "Mushroom button", marathi: "मशरूम", gramsPerExchange: 9.9 },
    { name: "Broccoli", marathi: "ब्रोकोली", gramsPerExchange: 16.0 },
    { name: "Tinda (Dhemse)", marathi: "धेमसे / टिंडा", gramsPerExchange: 33.9 },
    { name: "Ash gourd (Kohla/Petha)", marathi: "कोहळा / पेठा", gramsPerExchange: 49.5 },
    { name: "Peas fresh (Matar)", marathi: "मटार (ताजे)", gramsPerExchange: 6.5 },
    { name: "Raw papaya (Kachchi papai)", marathi: "कच्ची पपई", gramsPerExchange: 126.6 },
    { name: "Raw mango (Kairi)", marathi: "कैरी", gramsPerExchange: 50.1 },
    { name: "Parwar (Parval)", marathi: "परवर", gramsPerExchange: 24.0 },
    { name: "Tondli (Kovai)", marathi: "तोंडली", gramsPerExchange: 29.0 },
    { name: "Spinach (Palak)", marathi: "पालक", gramsPerExchange: 16.0 },
    { name: "Cabbage (Kobi)", marathi: "कोबी", gramsPerExchange: 47.6 },
    { name: "Fenugreek leaves (Methi)", marathi: "मेथी", gramsPerExchange: 8.7 },
    { name: "Coriander leaves (Kothimbir)", marathi: "कोथिंबीर", gramsPerExchange: 8.8 },
    { name: "Colocasia leaves (Aluchi pane)", marathi: "अळूची पाने", gramsPerExchange: 12.6 },
    { name: "Amaranth leaves (Math bhaji)", marathi: "माठ भाजी", gramsPerExchange: 12.1 },
    { name: "Curry leaves (Kadhipatta)", marathi: "कढीपत्ता", gramsPerExchange: 6.9 },
    { name: "Dill leaves (Shepu)", marathi: "शेपू", gramsPerExchange: 13.0 },
    { name: "Bamboo shoot tender", marathi: "बांबूचे कोंब", gramsPerExchange: 40.8 },
    { name: "Bean scarlet tender (Chavli shenga)", marathi: "चवळीच्या शेंगा", gramsPerExchange: 15.4 },
    { name: "Bean snap yellow raw", gramsPerExchange: 22.2 },
    { name: "Bottle gourd elongate pale green", marathi: "लांब दुधी भोपळा", gramsPerExchange: 57.3 },
    { name: "Bottle gourd round pale green", marathi: "गोल दुधी भोपळा", gramsPerExchange: 71.7 },
    { name: "Broad beans (Ghevda)", marathi: "घेवडा", gramsPerExchange: 9.6 },
    { name: "Broad beans immature seeds boiled", marathi: "शिजवलेला घेवडा", gramsPerExchange: 8.5 },
    { name: "Broad beans immature seeds raw", marathi: "कच्चा घेवडा", gramsPerExchange: 7.3 },
    { name: "Broccoli flower", marathi: "ब्रोकोली फूल", gramsPerExchange: 15.6 },
    { name: "Capsicum yellow", marathi: "सिमला मिरची (पिवळी)", gramsPerExchange: 28.3 },
    { name: "Celery stalk", marathi: "सेलेरी", gramsPerExchange: 44.0 },
    { name: "Chili red fresh", marathi: "लाल मिरची (ताजी)", gramsPerExchange: 23.8 },
    { name: "Cho-cho marrow", gramsPerExchange: 45.2 },
    { name: "Colocasia stem black (Alu dande)", marathi: "अळूचे देठ (काळे)", gramsPerExchange: 44.2 },
    { name: "Colocasia stem green (Alu dande)", marathi: "अळूचे देठ (हिरवे)", gramsPerExchange: 36.9 },
    { name: "Corn baby", marathi: "बेबी कॉर्न", gramsPerExchange: 15.3 },
    { name: "Cowpea immature seeds (Chavli dane)", marathi: "चवळीचे दाणे", gramsPerExchange: 11.7 },
    { name: "Cucumber orange round", marathi: "गोल काकडी", gramsPerExchange: 33.3 },
    { name: "Field beans immature seeds raw (Wal)", marathi: "कच्चे वाल", gramsPerExchange: 12.9 },
    { name: "Field beans immature seeds boiled (Wal)", marathi: "शिजवलेले वाल", gramsPerExchange: 9.2 },
    { name: "Field beans tender broad (Ghevda)", marathi: "घेवडा (रुंद)", gramsPerExchange: 12.8 },
    { name: "Field beans tender lean (Ghevda)", marathi: "घेवडा (पातळ)", gramsPerExchange: 10.3 },
    { name: "French beans hybrid (Farsabi)", marathi: "हायब्रीड फरसबी", gramsPerExchange: 15.8 },
    { name: "Jackfruit raw (Kachcha phanas)", marathi: "कच्चा फणस", gramsPerExchange: 17.9 },
    { name: "Jackfruit seed mature (Athalya)", marathi: "फणसाच्या आठळ्या", gramsPerExchange: 5.0 },
    { name: "Knol-Khol (Navalkol)", marathi: "नवलकोल", gramsPerExchange: 23.8 },
    { name: "Kovai small (Tondli chote)", marathi: "छोटी तोंडली", gramsPerExchange: 32.5 },
    { name: "Lima beans immature seeds", gramsPerExchange: 4.7 },
    { name: "Lima beans immature seeds boiled", gramsPerExchange: 4.7 },
    { name: "Maize tender local (Pand maka)", marathi: "पांढरा मका", gramsPerExchange: 15.8 },
    { name: "Maize tender sweet (Pivla maka)", marathi: "पिवळा मका", gramsPerExchange: 12.4 },
    { name: "Mushroom brown", marathi: "तपकिरी मशरूम", gramsPerExchange: 17.4 },
    { name: "Mushroom chicken fresh", gramsPerExchange: 20.3 },
    { name: "Mushroom oyster dried", marathi: "सुके ऑयस्टर मशरूम", gramsPerExchange: 1.7 },
    { name: "Mushroom shiitake fresh", marathi: "शिताके मशरूम", gramsPerExchange: 10.3 },
    { name: "Peas green boiled", marathi: "शिजवलेले मटार", gramsPerExchange: 8.6 },
    { name: "Peas green frozen", marathi: "गोठवलेले मटार", gramsPerExchange: 8.8 },
    { name: "Pepper jalapeno raw (Bhaji chi mirchi)", marathi: "भाजी मिरची", gramsPerExchange: 35.1 },
    { name: "Plantain flower (Kelphul)", marathi: "केळफूल", gramsPerExchange: 28.6 },
    { name: "Plantain stem (Kelichi khunt)", marathi: "केळीचा खुंट", gramsPerExchange: 97.8 },
    { name: "Pumpkin green cylindrical", marathi: "हिरवा भोपळा (लांब)", gramsPerExchange: 38.5 },
    { name: "Pumpkin orange round", marathi: "केशरी गोल भोपळा", gramsPerExchange: 39.4 },
    { name: "Red gram tender fresh (Turichi shenga)", marathi: "तुरीच्या शेंगा", gramsPerExchange: 5.7 },
    { name: "Ridge gourd smooth (Dodka)", marathi: "दोडका", gramsPerExchange: 34.1 },
    { name: "Snake gourd long pale green (Padwal)", marathi: "लांब पडवळ", gramsPerExchange: 36.1 },
    { name: "Snake gourd short (Padwal)", marathi: "आखूड पडवळ", gramsPerExchange: 68.6 },
    { name: "Snow pea edible podded raw", marathi: "बर्फातील वाटाणे", gramsPerExchange: 7.3 },
    { name: "Soybeans green", marathi: "हिरवे सोयाबीन", gramsPerExchange: 3.5 },
    { name: "Squash summer (Ghosale)", marathi: "घोसाळे", gramsPerExchange: 37.7 },
    { name: "Squash winter (Ghosale)", marathi: "हिवाळी घोसाळे", gramsPerExchange: 32.3 },
    { name: "Tomato orange", marathi: "नारिंगी टोमॅटो", gramsPerExchange: 66.7 },
    { name: "Tomato yellow", marathi: "पिवळा टोमॅटो", gramsPerExchange: 80.0 },
    { name: "Tomato green", marathi: "हिरवा टोमॅटो", gramsPerExchange: 57.8 },
    { name: "Tomato ripe hybrid", marathi: "हायब्रीड टोमॅटो", gramsPerExchange: 96.0 },
    { name: "Turnip (Salgam)", marathi: "सलगम", gramsPerExchange: 66.7 },
    { name: "Yardlong beans dark green (Chavli shenga)", marathi: "गडद हिरव्या चवळीच्या शेंगा", gramsPerExchange: 12.3 },
    { name: "Zucchini yellow", marathi: "पिवळी झुकिनी", gramsPerExchange: 26.7 },
  ],

  "leafy vegetables": [
    { name: "Agathi leaves", gramsPerExchange: 4.2 },
    { name: "Amaranth leaves red (Math bhaji lal)", marathi: "लाल माठ भाजी", gramsPerExchange: 9.7 },
    { name: "Amaranth leaves red and green mix", marathi: "माठ भाजी (लाल-हिरवी)", gramsPerExchange: 13.0 },
    { name: "Amaranth spinosus leaves green (Katewala math)", marathi: "काटेवाला माठ", gramsPerExchange: 13.5 },
    { name: "Amaranth spinosus leaves red and green mix", marathi: "काटेवाला माठ (लाल-हिरवा)", gramsPerExchange: 17.3 },
    { name: "Asparagus raw (Shatavari)", marathi: "शतावरी", gramsPerExchange: 17.4 },
    { name: "Asparagus cooked (Shatavari)", marathi: "शिजवलेली शतावरी", gramsPerExchange: 16.0 },
    { name: "Basella leaves (Mayalu)", marathi: "मायाळू", gramsPerExchange: 32.8 },
    { name: "Bathua leaves (Chakwat)", marathi: "चाकवत", gramsPerExchange: 13.2 },
    { name: "Beet greens (Bitachi pane)", marathi: "बीटाची पाने", gramsPerExchange: 19.7 },
    { name: "Betel leaves big Kolkata (Vida paan)", marathi: "विडा पान (मोठे)", gramsPerExchange: 23.0 },
    { name: "Betel leaves small (Vida paan)", marathi: "विडा पान (छोटे)", gramsPerExchange: 19.4 },
    { name: "Brussels sprout", marathi: "ब्रसेल्स स्प्राउट", gramsPerExchange: 9.9 },
    { name: "Cabbage collard greens", gramsPerExchange: 9.8 },
    { name: "Cabbage chinese", marathi: "चायनीज कोबी", gramsPerExchange: 30.3 },
    { name: "Cabbage chinese pe-tsai raw", marathi: "पे-त्साई कोबी", gramsPerExchange: 37.7 },
    { name: "Cabbage green (Hirva kobi)", marathi: "हिरवी कोबी", gramsPerExchange: 30.4 },
    { name: "Cabbage violet (Lal kobi)", marathi: "लाल कोबी", gramsPerExchange: 26.3 },
    { name: "Cauliflower leaves", marathi: "फुलकोबीची पाने", gramsPerExchange: 10.4 },
    { name: "Celery leaves (Selari)", marathi: "सेलेरी पाने", gramsPerExchange: 74.1 },
    { name: "Chard swiss (Silver beet)", gramsPerExchange: 18.2 },
    { name: "Chard swiss boiled", gramsPerExchange: 17.5 },
    { name: "Chives raw", gramsPerExchange: 13.8 },
    { name: "Drumstick leaves (Shevgyacha pala)", marathi: "शेवग्याची पाने", gramsPerExchange: 7.1 },
    { name: "Knol-Khol leaves (Navalkol pane)", marathi: "नवलकोलची पाने", gramsPerExchange: 11.2 },
    { name: "Leeks raw", marathi: "लीक्स", gramsPerExchange: 35.7 },
    { name: "Leeks boiled", marathi: "शिजवलेले लीक्स", gramsPerExchange: 64.5 },
    { name: "Lettuce green leaf", marathi: "लेट्यूस (हिरवे)", gramsPerExchange: 28.6 },
    { name: "Lettuce iceberg", marathi: "आइसबर्ग लेट्यूस", gramsPerExchange: 83.3 },
    { name: "Lettuce red leaf", marathi: "लेट्यूस (लाल)", gramsPerExchange: 41.7 },
    { name: "Lettuce romaine", marathi: "रोमेन लेट्यूस", gramsPerExchange: 36.4 },
    { name: "Mint leaves (Pudina)", marathi: "पुदिना", gramsPerExchange: 7.5 },
    { name: "Mustard leaves (Mohri pane)", marathi: "मोहरीची पाने", gramsPerExchange: 16.1 },
    { name: "Onion stalk (Kandyachya pati)", marathi: "कांद्याची पात", gramsPerExchange: 16.4 },
    { name: "Pak Choi leaves", marathi: "पाक चोई", gramsPerExchange: 25.0 },
    { name: "Parsley (English kothimbir)", marathi: "इंग्रजी कोथिंबीर", gramsPerExchange: 5.8 },
    { name: "Ponnaganni", gramsPerExchange: 6.4 },
    { name: "Pumpkin leaves tender (Bhoplya pane)", marathi: "भोपळ्याची पाने", gramsPerExchange: 8.2 },
    { name: "Radish leaves (Mulyachi pane)", marathi: "मुळ्याची पाने", gramsPerExchange: 21.1 },
    { name: "Rumex leaves (Ambada)", marathi: "अंबाडा", gramsPerExchange: 31.1 },
    { name: "Seaweed spirulina", marathi: "स्पिरुलिना", gramsPerExchange: 5.5 },
    { name: "Spring onions top and bulb", marathi: "हिरव्या कांद्याची पात", gramsPerExchange: 24.7 },
    { name: "Tamarind leaves tender (Chinchecha pala)", marathi: "चिंचेची पाने", gramsPerExchange: 6.1 },
    { name: "Turnip greens (Salgam chi pane)", marathi: "सलगमची पाने", gramsPerExchange: 19.6 },
    { name: "Turnip greens boiled", marathi: "शिजवलेली सलगमची पाने", gramsPerExchange: 25.6 },
    { name: "Watercress (Aliv bhaji)", marathi: "अळिव भाजी", gramsPerExchange: 14.6 },
  ],

  "root vegetables": [
    { name: "Potato (Batata)", marathi: "बटाटा", gramsPerExchange: 30.3 },
    { name: "Potato boiled", marathi: "उकडलेला बटाटा", gramsPerExchange: 20.0 },
    { name: "Carrot (Gajar)", marathi: "गाजर", gramsPerExchange: 46.0 },
    { name: "Beet root (Bit)", marathi: "बीट", gramsPerExchange: 18.3 },
    { name: "Onion big (Kanda)", marathi: "कांदा (मोठा)", gramsPerExchange: 48.5 },
    { name: "Onion small (Shallots)", marathi: "छोटा कांदा / शेलॉट्स", gramsPerExchange: 28.0 },
    { name: "Sweet potato (Ratale)", marathi: "रताळे", gramsPerExchange: 27.0 },
    { name: "Colocasia (Alkudi/Arabi)", marathi: "अळूकडी / अरबी", gramsPerExchange: 11.3 },
    { name: "Radish white (Mula)", marathi: "पांढरा मुळा", gramsPerExchange: 46.6 },
    { name: "Plantain green (Kachche kele)", marathi: "कच्चे केळे", gramsPerExchange: 30.8 },
    { name: "Yam (Suran)", marathi: "सुरण", gramsPerExchange: 19.9 },
    { name: "Tapioca (Simla batata)", marathi: "सिमला बटाटा / टॅपिओका", gramsPerExchange: 41.1 },
    { name: "Lotus root (Kamal kakdi)", marathi: "कमळ काकडी", gramsPerExchange: 22.6 },
    { name: "Casava", marathi: "कसावा", gramsPerExchange: 57.1 },
    { name: "Carrot red (Gajar lal)", marathi: "लाल गाजर", gramsPerExchange: 43.0 },
    { name: "Carrots baby raw", marathi: "बेबी गाजर", gramsPerExchange: 55.6 },
    { name: "Onion sweet (Safed kanda)", marathi: "सफेद कांदा", gramsPerExchange: 100.0 },
    { name: "Potato boiled with skin", marathi: "सालासकट उकडलेला बटाटा", gramsPerExchange: 19.0 },
    { name: "Potato boiled without skin", marathi: "सालाशिवाय उकडलेला बटाटा", gramsPerExchange: 20.8 },
    { name: "Potato brown skin small", marathi: "तपकिरी सालाचा छोटा बटाटा", gramsPerExchange: 35.0 },
    { name: "Potato red skin", marathi: "लाल सालाचा बटाटा", gramsPerExchange: 33.5 },
    { name: "Radish elongate red skin (Mula lal)", marathi: "लाल मुळा", gramsPerExchange: 58.0 },
    { name: "Radish round red skin", marathi: "गोल लाल मुळा", gramsPerExchange: 42.6 },
    { name: "Radish round white skin", marathi: "गोल पांढरा मुळा", gramsPerExchange: 48.3 },
    { name: "Shallots small (Chote kande)", marathi: "छोटे कांदे", gramsPerExchange: 18.2 },
    { name: "Sweet potato pink skin (Ratale gulabi)", marathi: "गुलाबी रताळे", gramsPerExchange: 27.5 },
    { name: "Water chestnut (Shingada)", marathi: "शिंगाडा", gramsPerExchange: 61.2 },
    { name: "Yam elephant (Suran)", marathi: "सुरण (हत्ती सुरण)", gramsPerExchange: 13.4 },
    { name: "Yam wild (Suran ran)", marathi: "रान सुरण", gramsPerExchange: 10.9 },
  ],

  "free group": [
    { name: "Sago / Arrowroot (Sabudana)", marathi: "साबुदाणा", gramsPerExchange: 14 },
    { name: "Corn Starch (Cornflour)", marathi: "कॉर्नफ्लोअर", gramsPerExchange: 13 },
    { name: "Wheat Starch", marathi: "गव्हाचे स्टार्च", gramsPerExchange: 14 },
    { name: "Maize Corn Starch", marathi: "मक्याचे स्टार्च", gramsPerExchange: 14 },
    { name: "Mixed Fruit Jam", marathi: "मिश्र फळांचा जॅम", gramsPerExchange: 18 },
    { name: "Molasses", marathi: "मळी / मेलास", gramsPerExchange: 17 },
    { name: "Custard Powder", marathi: "कस्टर्ड पावडर", gramsPerExchange: 13 },
    { name: "Corn Syrup (Light)", marathi: "कॉर्न सिरप", gramsPerExchange: 18 },
    { name: "Rice Milk", marathi: "तांदळाचे दूध", gramsPerExchange: 105, unit: "ml" },
    { name: "Aam Papad", marathi: "आमपापड", gramsPerExchange: 16 },
    { name: "Gulkand", marathi: "गुलकंद", gramsPerExchange: 18 },
    { name: "Ice cream (Creambell)", marathi: "आइस्क्रीम", gramsPerExchange: 41 },
    { name: "Mapro Mixed Fruit Jam", gramsPerExchange: 19 },
    { name: "Patanjali Mixed Fruit Jam", gramsPerExchange: 17 },
    { name: "Potato Starch", marathi: "बटाट्याचे स्टार्च", gramsPerExchange: 15 },
    { name: "Corn Syrup Dark", marathi: "गडद कॉर्न सिरप", gramsPerExchange: 17, unit: "ml" },
    { name: "Wikfield Cornflour", gramsPerExchange: 14 },
  ],

  miscellaneous: [
    { name: "Mango ginger (Ambehalad)", marathi: "अंबेहळद", gramsPerExchange: 7.2 },
    { name: "Jaggery cane (Gul)", marathi: "गूळ", gramsPerExchange: 7.8 },
    { name: "Coconut milk (Nariyal doodh)", marathi: "नारळाचे दूध", gramsPerExchange: 3.6 },
    { name: "Coconut water (Naral pani)", marathi: "नारळ पाणी", gramsPerExchange: 63.7 },
    { name: "Coconut kernel dry (Suka khobra)", marathi: "सुके खोबरे", gramsPerExchange: 1.4 },
    { name: "Coconut kernel fresh (Ola khobra)", marathi: "ओले खोबरे", gramsPerExchange: 2.2 },
    { name: "Tomato juice canned", marathi: "टोमॅटो ज्यूस", gramsPerExchange: 29.4 },
    { name: "Tomato paste without salt", marathi: "टोमॅटो पेस्ट", gramsPerExchange: 5.7 },
    { name: "Tomato puree", marathi: "टोमॅटो प्युरी", gramsPerExchange: 15.2 },
    { name: "Tomato sauce", marathi: "टोमॅटो सॉस", gramsPerExchange: 18.5 },
    { name: "Butter (Loni)", marathi: "लोणी", gramsPerExchange: 8.8 },
  ],

  candies: [
    { name: "4 Fruits Pudding Jelly", gramsPerExchange: 63 },
    { name: "Ahmed Jelly Crystal Lychee Jelly", gramsPerExchange: 14 },
    { name: "Alpenliebe Jutz Jelly Fruity Bars", gramsPerExchange: 16 },
    { name: "Alpenliebe Mangofillz", gramsPerExchange: 13 },
    { name: "Alpenliebe Pop", gramsPerExchange: 12 },
    { name: "Brookside dark exotic chocolate", gramsPerExchange: 11 },
    { name: "Candies Butterscotch", gramsPerExchange: 13 },
    { name: "Candies Gumdrops (Starch Jelly)", gramsPerExchange: 13 },
    { name: "Candies Hard", gramsPerExchange: 13 },
    { name: "Candies Jelly Beans", gramsPerExchange: 13 },
    { name: "Candyman Jellicious Jelimals", gramsPerExchange: 15 },
    { name: "Candyman Jellicious With Real Strawberry Pulp", gramsPerExchange: 15 },
    { name: "Chewing Gum", gramsPerExchange: 14 },
    { name: "Confeito Chocolate Vermicelli", gramsPerExchange: 50 },
    { name: "Confeito Rainbow Vermicelli", gramsPerExchange: 50 },
    { name: "Crush Pop (Lolipop) Mix Fruit", gramsPerExchange: 13 },
    { name: "Darling Velvetto", gramsPerExchange: 13 },
    { name: "Falchoos", gramsPerExchange: 17 },
    { name: "Falero (Jamun)", gramsPerExchange: 17 },
    { name: "Falero (Kacchi Kairy)", gramsPerExchange: 17 },
    { name: "Falero (Strawberry)", gramsPerExchange: 18 },
    { name: "Falero Pineapple", gramsPerExchange: 17 },
    { name: "Falero Wahwah Guava", gramsPerExchange: 17 },
    { name: "Fox Crystal Clear", gramsPerExchange: 16 },
    { name: "Fru Asorted Pack", gramsPerExchange: 16 },
    { name: "Frubbles Fruit Pebbles Purple Colour", gramsPerExchange: 16 },
    { name: "Frubbles Fruit Pebbles Yellow Colour", gramsPerExchange: 16 },
    { name: "Galaxy Real Jelly Sweets", gramsPerExchange: 17 },
    { name: "Geeef Magic Pops", gramsPerExchange: 14 },
    { name: "Glucovita Bolts Orange", gramsPerExchange: 14 },
    { name: "Gula Gula", gramsPerExchange: 15 },
    { name: "Harmik Phantom Sweet Cigarette Candy", gramsPerExchange: 13 },
    { name: "Jellies", gramsPerExchange: 19 },
    { name: "Jolly Rancher Chews Mixed Fruit", gramsPerExchange: 13 },
    { name: "Jolly Rancher Hard Candy", gramsPerExchange: 13 },
    { name: "Jolly Rancher Lollipops", gramsPerExchange: 13 },
    { name: "Just Jelly (Guava)", gramsPerExchange: 16 },
    { name: "Just Jelly (Kacchi Kairy)", gramsPerExchange: 16 },
    { name: "Just Jelly (Litchi)", gramsPerExchange: 16 },
    { name: "Just Jelly (Strawberry)", gramsPerExchange: 16 },
    { name: "Justjelly Fruity Bear", gramsPerExchange: 16 },
    { name: "Luvit Crazy Maker Lolipop Fruit Flavour", gramsPerExchange: 13 },
    { name: "Mala's Froogle Fruity Chews", gramsPerExchange: 14 },
    { name: "Mala's Butter Scotch Apple", gramsPerExchange: 19 },
    { name: "Mala's Melties Lichi", gramsPerExchange: 49 },
    { name: "Mala's Melties Mango", gramsPerExchange: 49 },
    { name: "Mapro Falchoos", gramsPerExchange: 17 },
    { name: "Mapro Fruity Sweet", gramsPerExchange: 17 },
    { name: "Mazelo Flavour Candy", gramsPerExchange: 13 },
    { name: "Mentos", gramsPerExchange: 14 },
    { name: "Nilons Fruits (Tooty Fruity)", gramsPerExchange: 17 },
    { name: "Parle Fruit Jelly Mixed", gramsPerExchange: 15 },
    { name: "Parle Kaccha Mango Bite", gramsPerExchange: 13 },
    { name: "Passpass Pulse Guava With Tangy Twist", gramsPerExchange: 13 },
    { name: "Passpass Pulse Kachcha Aam With Tangy Twist", gramsPerExchange: 13 },
    { name: "Tic Tac", gramsPerExchange: 13 },
  ],

  juices: [
    { name: "Active Fiber+", gramsPerExchange: 94, unit: "ml" },
    { name: "B Natural Guava", gramsPerExchange: 83, unit: "ml" },
    { name: "B Natural Lichi", gramsPerExchange: 91, unit: "ml" },
    { name: "B Natural Orange", gramsPerExchange: 89, unit: "ml" },
    { name: "B Natural Pineapple", gramsPerExchange: 88, unit: "ml" },
    { name: "Del Monte Green Apple", gramsPerExchange: 110, unit: "ml" },
    { name: "Del Monte Mango", gramsPerExchange: 81, unit: "ml" },
    { name: "Del Monte Pineapple", gramsPerExchange: 94, unit: "ml" },
    { name: "Delmonte Four Season Mixed Fruit", gramsPerExchange: 98, unit: "ml" },
    { name: "Euro Fresho Mango Juice", gramsPerExchange: 77, unit: "ml" },
    { name: "Euro Fresho Litchi", gramsPerExchange: 89, unit: "ml" },
    { name: "Euro Fresho Mango Pulp", gramsPerExchange: 77, unit: "ml" },
    { name: "Frooti Mango Drink", gramsPerExchange: 77 },
    { name: "Hershey's Syrup Strawberry", gramsPerExchange: 18, unit: "ml" },
    { name: "KISSAN Lemon Squash", gramsPerExchange: 25, unit: "ml" },
    { name: "Kissan Mango Squash", gramsPerExchange: 23, unit: "ml" },
    { name: "Lichika Lichi Drink", gramsPerExchange: 86, unit: "ml" },
    { name: "Mala's Lichi Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mala's Mango Squash", gramsPerExchange: 27, unit: "ml" },
    { name: "Mala's Strawberry Crush", gramsPerExchange: 20, unit: "ml" },
    { name: "Mala's Pineapple Crush", gramsPerExchange: 22, unit: "ml" },
    { name: "Mala's Green Apple Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mala's Banana Crush", gramsPerExchange: 17, unit: "ml" },
    { name: "Maple Syrup", gramsPerExchange: 19, unit: "ml" },
    { name: "Mapro Rose Sharbat", gramsPerExchange: 14, unit: "ml" },
    { name: "Mapro Mango Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Litchi Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Kiwi Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Green Apple Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Pinacolada Squash", gramsPerExchange: 16, unit: "ml" },
    { name: "Marmalade Orange", gramsPerExchange: 20 },
    { name: "Maza Gold Tetra Pack", gramsPerExchange: 89, unit: "ml" },
    { name: "Mazza Mango", gramsPerExchange: 93, unit: "ml" },
    { name: "Minute Maid Mosambi", gramsPerExchange: 104, unit: "ml" },
    { name: "Minute Maid Mango", gramsPerExchange: 78, unit: "ml" },
    { name: "Minute Maid Mixed Fruit", gramsPerExchange: 89, unit: "ml" },
    { name: "Mrs. Food Rite Rose Sharbat", gramsPerExchange: 14, unit: "ml" },
    { name: "Mushy Mango Rush (CCD)", gramsPerExchange: 89, unit: "ml" },
    { name: "Paper Boat Jaljeera", gramsPerExchange: 109, unit: "ml" },
    { name: "Paper Boat Guava", gramsPerExchange: 105, unit: "ml" },
    { name: "Paper Boat Mixed Fruit", gramsPerExchange: 105, unit: "ml" },
    { name: "Paper Boat Aampanna", gramsPerExchange: 104, unit: "ml" },
    { name: "Paper Boat Anar", gramsPerExchange: 106, unit: "ml" },
    { name: "Patanjali Guava", gramsPerExchange: 80, unit: "ml" },
    { name: "Patanjali Mango", gramsPerExchange: 77, unit: "ml" },
    { name: "Pran Litchi Drink", gramsPerExchange: 96, unit: "ml" },
    { name: "Rasna Apple", gramsPerExchange: 13 },
    { name: "Rasna Mango", gramsPerExchange: 13 },
    { name: "Rasna Nimbupani", gramsPerExchange: 13 },
    { name: "Rasna Orange", gramsPerExchange: 13 },
    { name: "Real Apple", gramsPerExchange: 83, unit: "ml" },
    { name: "Real Lichi", gramsPerExchange: 83, unit: "ml" },
    { name: "Real Mango", gramsPerExchange: 82, unit: "ml" },
    { name: "Real Orange", gramsPerExchange: 89, unit: "ml" },
    { name: "Real Active Fiber+", gramsPerExchange: 94, unit: "ml" },
    { name: "Real Pineapple", gramsPerExchange: 89, unit: "ml" },
    { name: "Real Pomegranate", gramsPerExchange: 83, unit: "ml" },
    { name: "Syrup Fruit", gramsPerExchange: 15, unit: "ml" },
    { name: "Syrup Nestle Chocolate", gramsPerExchange: 19, unit: "ml" },
    { name: "Tang Mango", gramsPerExchange: 13 },
    { name: "Tang Nimbupani", gramsPerExchange: 13 },
    { name: "Tang Orange", gramsPerExchange: 13 },
    { name: "Tropicana Apple", gramsPerExchange: 104, unit: "ml" },
    { name: "Tropicana Essentials Fruit & Veggies", gramsPerExchange: 106, unit: "ml" },
    { name: "Tropicana Lichi", gramsPerExchange: 86, unit: "ml" },
    { name: "Tropicana Mango", gramsPerExchange: 82, unit: "ml" },
    { name: "Tropicana Orange", gramsPerExchange: 96, unit: "ml" },
    { name: "Tropicana Pomegranate", gramsPerExchange: 89, unit: "ml" },
    { name: "Tropicana Slice Juice", gramsPerExchange: 76, unit: "ml" },
    { name: "Tropicana Pineapple", gramsPerExchange: 93, unit: "ml" },
    { name: "Guruji's Orange Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Manama Mango Crush", gramsPerExchange: 20 },
    { name: "Macro Alphonso Mango Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Alo Fruit Berries", gramsPerExchange: 86, unit: "ml" },
    { name: "Coffee Day Mushy Mango", gramsPerExchange: 89, unit: "ml" },
    { name: "Jeeru Jeera Masala", gramsPerExchange: 114, unit: "ml" },
    { name: "Cravova Peach Majito", gramsPerExchange: 89, unit: "ml" },
    { name: "Baskin Robbins Raspberry Sorbet small scoop", gramsPerExchange: 56, unit: "ml" },
  ],

  "sugar coated dried fruits": [
    { name: "Cranberries dried sweetened", gramsPerExchange: 16 },
    { name: "Flyberry dehydrated pineapple", gramsPerExchange: 15 },
    { name: "Flyberry raspberry", gramsPerExchange: 15 },
    { name: "Gourima amla candy", gramsPerExchange: 15 },
    { name: "Gourima dried kiwis", gramsPerExchange: 14 },
    { name: "Gourima fruit mix", gramsPerExchange: 14 },
    { name: "Happilo dried mango", gramsPerExchange: 13 },
    { name: "Nourish amla candy", gramsPerExchange: 15 },
    { name: "Nourish cranberry candy", gramsPerExchange: 14 },
    { name: "Nourish guava candy", gramsPerExchange: 13 },
    { name: "Nourish mango candy", gramsPerExchange: 14 },
    { name: "Nourish mixed fruits", gramsPerExchange: 14 },
    { name: "Nourish pineapple candy", gramsPerExchange: 13 },
    { name: "Nutriplato fruit chunks", gramsPerExchange: 14 },
    { name: "Regency dried cranberries slice", gramsPerExchange: 14 },
    { name: "Regency dried cranberries whole", gramsPerExchange: 14 },
    { name: "Welch's fruit snacks", gramsPerExchange: 16 },
  ],

  "mayo and cheese": [
    { name: "So Good Almond Vanilla Milk", gramsPerExchange: 50, unit: "ml" },
    { name: "So Good Almond Chocolate Milk", gramsPerExchange: 38, unit: "ml" },
    { name: "Dabar Homemade Coconut Milk", gramsPerExchange: 35, unit: "ml" },
    { name: "Urban Platter Vegan Cheeze Sauce Mix", gramsPerExchange: 50 },
    { name: "World's First Vegan Jalapeno Cheese Dip", gramsPerExchange: 36 },
    { name: "Urban Platter Vegan Premium Mayo", gramsPerExchange: 30 },
    { name: "Bombay Cheese Company Cheddar", gramsPerExchange: 50 },
    { name: "Violife Mature Cheddar Slice", gramsPerExchange: 50 },
    { name: "Surabhi Mayonnaise", gramsPerExchange: 88 },
    { name: "Sheeze Grated Mozzerlla Style", gramsPerExchange: 300 },
    { name: "Grated Sheese Veg Mature Cheddar Style", gramsPerExchange: 43 },
    { name: "Hellmanns Light Mayo", gramsPerExchange: 60 },
  ],
};
