// Food exchange data extracted from dietitian PDFs (Dr. Sheetal M Preventa Clinic)
// Each entry: { name, gramsPerExchange }
// For categories measured in ml, unit: "ml" is specified.

export const FOOD_EXCHANGES = {
  cereal: [
    { name: "Rice", gramsPerExchange: 7.3 },
    { name: "Rice flakes (Pohe)", gramsPerExchange: 8.7 },
    { name: "Rice puffed (Murmure)", gramsPerExchange: 8.7 },
    { name: "Rice flour", gramsPerExchange: 10.1 },
    { name: "Ragi (Nachni)", gramsPerExchange: 8.7 },
    { name: "Ragi flour", gramsPerExchange: 7.2 },
    { name: "Wheat flour (Atta)", gramsPerExchange: 6.5 },
    { name: "Wheat Semolina (Rava/Suji)", gramsPerExchange: 6.9 },
    { name: "Wheat vermicelli (Shevya)", gramsPerExchange: 10.2 },
    { name: "Millet (Bajri)", gramsPerExchange: 6.7 },
    { name: "Millet flour (Bajricha pith)", gramsPerExchange: 6.0 },
    { name: "Sorghum (Jowar)", gramsPerExchange: 7.8 },
    { name: "Sorghum flour (Jowar pith)", gramsPerExchange: 9.0 },
    { name: "Corn flour", gramsPerExchange: 10.0 },
    { name: "Samai (Sama/Vari)", gramsPerExchange: 6.5 },
    { name: "Amaranth seeds (Rajgira)", gramsPerExchange: 5.5 },
    { name: "Buckwheat (Kuttu)", gramsPerExchange: 5.2 },
    { name: "Oats", gramsPerExchange: 3.7 },
    { name: "Quinoa", gramsPerExchange: 5.9 },
    { name: "Varagu", gramsPerExchange: 7.1 },
    { name: "Barley pearled (Satu)", gramsPerExchange: 6.7 },
    { name: "Bread white (Pav)", gramsPerExchange: 10.4 },
    { name: "Bread wheat", gramsPerExchange: 13.5 },
    { name: "Pasta dry", gramsPerExchange: 6.0 },
    { name: "Pasta corn dry", gramsPerExchange: 9.3 },
    { name: "Rice noodles dry", gramsPerExchange: 10.1 },
    { name: "Macaroni dry", gramsPerExchange: 6.0 },
    { name: "Bulgur dry (Lapshi rava)", gramsPerExchange: 7.5 },
    { name: "Toast rusk", gramsPerExchange: 5.1 },
    { name: "Rice parboiled (Ukde tandul)", gramsPerExchange: 7.2 },
    { name: "Amaranth seeds pale brown (Rajgira)", gramsPerExchange: 6.1 },
    { name: "Bread crumbs", gramsPerExchange: 5.8 },
    { name: "Bread multi-grain", gramsPerExchange: 8.8 },
    { name: "Bread pita whole wheat", gramsPerExchange: 7.9 },
    { name: "Bread pita white", gramsPerExchange: 8.9 },
    { name: "Bread stick", gramsPerExchange: 6.8 },
    { name: "Brown rice flakes", gramsPerExchange: 9.3 },
    { name: "Couscous dry", gramsPerExchange: 6.4 },
    { name: "Couscous cooked", gramsPerExchange: 21.6 },
    { name: "Ice cream cones (wafer)", gramsPerExchange: 10.3 },
    { name: "Macaroni cooked", gramsPerExchange: 13.4 },
    { name: "Macaroni whole wheat dry", gramsPerExchange: 5.5 },
    { name: "Macaroni whole wheat cooked", gramsPerExchange: 15.2 },
    { name: "Maize dry", gramsPerExchange: 7.4 },
    { name: "Millet cooked (Bajri)", gramsPerExchange: 19.0 },
    { name: "Noodles Chinese chow Mein", gramsPerExchange: 9.9 },
    { name: "Noodles rice cooked", gramsPerExchange: 33.7 },
    { name: "Oats bran", gramsPerExchange: 3.6 },
    { name: "Oats bran cooked", gramsPerExchange: 21.2 },
    { name: "Pasta cooked", gramsPerExchange: 13.4 },
    { name: "Pasta corn cooked", gramsPerExchange: 26.3 },
    { name: "Pasta whole wheat cooked", gramsPerExchange: 13.5 },
    { name: "Quinoa cooked", gramsPerExchange: 18.9 },
    { name: "Rice brown raw", gramsPerExchange: 5.7 },
    { name: "Rice brown cooked", gramsPerExchange: 23.2 },
    { name: "Rice flour brown", gramsPerExchange: 8.3 },
    { name: "Rice long grain", gramsPerExchange: 8.0 },
    { name: "Rice medium grain", gramsPerExchange: 8.7 },
    { name: "Rice parboiled cooked", gramsPerExchange: 18.9 },
    { name: "Rice short grain", gramsPerExchange: 8.8 },
    { name: "Spaghetti dry", gramsPerExchange: 6.0 },
    { name: "Spaghetti cooked", gramsPerExchange: 13.4 },
    { name: "Spaghetti whole wheat dry", gramsPerExchange: 5.5 },
    { name: "Spaghetti whole wheat cooked", gramsPerExchange: 15.2 },
    { name: "Wheat bulgur cooked (Lapshi rava)", gramsPerExchange: 25.2 },
    { name: "Wheat flour refined (Maida)", gramsPerExchange: 8.4 },
    { name: "Wheat vermicelli roasted", gramsPerExchange: 9.1 },
    { name: "Wheat whole grain (Gehun)", gramsPerExchange: 6.5 },
    { name: "Wild rice raw", gramsPerExchange: 4.1 },
    { name: "Wild rice cooked", gramsPerExchange: 15.1 },
  ],

  "fresh fruit": [
    { name: "Apple big", gramsPerExchange: 147.8 },
    { name: "Apple small", gramsPerExchange: 110.5 },
    { name: "Banana (Kela)", gramsPerExchange: 20.2 },
    { name: "Mango (Amba)", gramsPerExchange: 35.7 },
    { name: "Mango Kesar", gramsPerExchange: 53.1 },
    { name: "Papaya (Papaya)", gramsPerExchange: 90.9 },
    { name: "Guava (Peru)", gramsPerExchange: 37.5 },
    { name: "Watermelon (Kalingad)", gramsPerExchange: 70.0 },
    { name: "Grapes seedless green", gramsPerExchange: 89.6 },
    { name: "Orange (Santre)", gramsPerExchange: 37.5 },
    { name: "Sweet lime (Mosambi)", gramsPerExchange: 114.1 },
    { name: "Pomegranate (Dalimb)", gramsPerExchange: 47.0 },
    { name: "Pineapple (Ananas)", gramsPerExchange: 70.9 },
    { name: "Pear (Naspati)", gramsPerExchange: 81.7 },
    { name: "Sapota / Chikoo", gramsPerExchange: 32.4 },
    { name: "Kiwi", gramsPerExchange: 26.3 },
    { name: "Strawberries", gramsPerExchange: 34.3 },
    { name: "Jamun (Black berry)", gramsPerExchange: 24.8 },
    { name: "Custard apple (Sitaphal)", gramsPerExchange: 19.1 },
    { name: "Gooseberry (Awala)", gramsPerExchange: 147.6 },
    { name: "Jackfruit (Phanas)", gramsPerExchange: 10.6 },
    { name: "Musk melon (Kharbuza)", gramsPerExchange: 92.5 },
    { name: "Litchi", gramsPerExchange: 25.0 },
    { name: "Plums (Alubukhaar)", gramsPerExchange: 64.6 },
    { name: "Peach (Pich)", gramsPerExchange: 32.1 },
    { name: "Figs fresh (Anjir)", gramsPerExchange: 13.8 },
    { name: "Apple green", gramsPerExchange: 89.1 },
    { name: "Apple sauce", gramsPerExchange: 187.5 },
    { name: "Apple sauce unsweetened", gramsPerExchange: 187.5 },
    { name: "Apple Kashmir", gramsPerExchange: 132.9 },
    { name: "Apple golden", gramsPerExchange: 115.4 },
    { name: "Apple red with skin", gramsPerExchange: 125.0 },
    { name: "Apples without skin", gramsPerExchange: 125.0 },
    { name: "Apricots fresh (Jardalu)", gramsPerExchange: 31.9 },
    { name: "Avocado (Makkhan phal)", gramsPerExchange: 11.4 },
    { name: "Bael fruit (Bel)", gramsPerExchange: 12.4 },
    { name: "Banana ripe red", gramsPerExchange: 17.7 },
    { name: "Banana ripe robusta", gramsPerExchange: 20.16 },
    { name: "Banana ripe montham", gramsPerExchange: 20.62 },
    { name: "Banana ripe poovam", gramsPerExchange: 16.5 },
    { name: "Blueberries", gramsPerExchange: 48.4 },
    { name: "Cherimoya (Maruti phal)", gramsPerExchange: 23.8 },
    { name: "Cherries sweet", gramsPerExchange: 21.1 },
    { name: "Crab apple (Jangali safarchand)", gramsPerExchange: 79.0 },
    { name: "Cranberries", gramsPerExchange: 33.3 },
    { name: "Currants black (Karwand)", gramsPerExchange: 19.4 },
    { name: "Elderberries", gramsPerExchange: 45.5 },
    { name: "Grapefruit pink", gramsPerExchange: 100.0 },
    { name: "Grapes seeded round black", gramsPerExchange: 75.9 },
    { name: "Grapes seeded round green", gramsPerExchange: 79.2 },
    { name: "Grapes seeded round red", gramsPerExchange: 55.8 },
    { name: "Grapes seedless oval black", gramsPerExchange: 39.0 },
    { name: "Grapes seedless round black", gramsPerExchange: 44.8 },
    { name: "Guava white", gramsPerExchange: 31.9 },
    { name: "Jambu fruit ripe (Safed jaam)", gramsPerExchange: 26.2 },
    { name: "Karonda fruit", gramsPerExchange: 28.2 },
    { name: "Lime (Nimbu)", gramsPerExchange: 126.2 },
    { name: "Longan fresh", gramsPerExchange: 25.9 },
    { name: "Mango banganapalli", gramsPerExchange: 46.9 },
    { name: "Mango gulabkhas", gramsPerExchange: 45.6 },
    { name: "Mango himsagar", gramsPerExchange: 67.0 },
    { name: "Mango neelam", gramsPerExchange: 35.1 },
    { name: "Mango paheri", gramsPerExchange: 36.0 },
    { name: "Mango totapuri", gramsPerExchange: 61.8 },
    { name: "Mangosteen", gramsPerExchange: 44.4 },
    { name: "Manila tamarind (Vilayati chinch)", gramsPerExchange: 8.6 },
    { name: "Musk melon orange flesh", gramsPerExchange: 107.3 },
    { name: "Nectarines", gramsPerExchange: 115.4 },
    { name: "Orange pulp (Santre)", gramsPerExchange: 101.1 },
    { name: "Palm fruit tender (Tadgola)", gramsPerExchange: 69.6 },
    { name: "Pears Asian", gramsPerExchange: 83.3 },
    { name: "Phalsa", gramsPerExchange: 15.7 },
    { name: "Pineapple chunks frozen", gramsPerExchange: 93.8 },
    { name: "Pummelo / Papanus", gramsPerExchange: 52.2 },
    { name: "Rambutan", gramsPerExchange: 46.2 },
    { name: "Soursop (Shul ramphal)", gramsPerExchange: 34.3 },
    { name: "Star fruit (Karambola)", gramsPerExchange: 45.1 },
    { name: "Tamarind pulp (Chinch)", gramsPerExchange: 12.8 },
    { name: "Tangerines mandarin oranges", gramsPerExchange: 71.4 },
    { name: "Watermelon dark green (sugar baby)", gramsPerExchange: 70.6 },
    { name: "Watermelon pale green", gramsPerExchange: 69.9 },
    { name: "Wood apple (Kawath)", gramsPerExchange: 12.8 },
    { name: "Zizyphus (Bor)", gramsPerExchange: 24.0 },
  ],

  "dried fruit": [
    { name: "Raisins (Bedana/Kishmish)", gramsPerExchange: 18.1 },
    { name: "Dates (Khajur)", gramsPerExchange: 44.6 },
    { name: "Dates dry (Kharik)", gramsPerExchange: 19.1 },
    { name: "Apricots dried (Suke Jardalu)", gramsPerExchange: 20.5 },
    { name: "Figs dried (Suke Anjir)", gramsPerExchange: 12.3 },
    { name: "Plums dried (Suke Alubukhaar)", gramsPerExchange: 26.8 },
    { name: "Pears dried (Suke Naspati)", gramsPerExchange: 22.7 },
    { name: "Apricot processed", gramsPerExchange: 48.1 },
    { name: "Apricots dried stewed unsweetened", gramsPerExchange: 53.6 },
    { name: "Apricots dried stewed with sugar", gramsPerExchange: 34.9 },
    { name: "Dates dry pale brown", gramsPerExchange: 21.5 },
    { name: "Figs dried stewed", gramsPerExchange: 28.3 },
    { name: "Goji berries dried", gramsPerExchange: 4.7 },
    { name: "Peach dried uncooked", gramsPerExchange: 7.6 },
    { name: "Peach dried stewed with sugar", gramsPerExchange: 25.9 },
    { name: "Peach dried stewed without sugar", gramsPerExchange: 23.8 },
    { name: "Pears dried stewed with sugar", gramsPerExchange: 50.0 },
    { name: "Pears dried stewed without sugar", gramsPerExchange: 46.9 },
    { name: "Raisins black dried (Manuka)", gramsPerExchange: 20.3 },
    { name: "Raisins golden (Kishmish)", gramsPerExchange: 19.1 },
  ],

  legumes: [
    { name: "Green gram whole (Mung)", gramsPerExchange: 1.6 },
    { name: "Green gram dal (Mug dal)", gramsPerExchange: 1.6 },
    { name: "Green gram sprouts (Mod mung)", gramsPerExchange: 15.4 },
    { name: "Red gram dal (Tur dal)", gramsPerExchange: 2.1 },
    { name: "Red gram whole (Turi)", gramsPerExchange: 2.3 },
    { name: "Bengal gram dal (Chana dal)", gramsPerExchange: 2.3 },
    { name: "Chick peas (Chane)", gramsPerExchange: 2.3 },
    { name: "Chick peas boiled", gramsPerExchange: 5.4 },
    { name: "Chickpea flour (Besan)", gramsPerExchange: 8.0 },
    { name: "Lentil dal (Masur dal)", gramsPerExchange: 1.6 },
    { name: "Lentil whole (Masur)", gramsPerExchange: 1.8 },
    { name: "Black gram whole (Urad)", gramsPerExchange: 2.2 },
    { name: "Moth bean (Matki)", gramsPerExchange: 2.1 },
    { name: "Rajmah red", gramsPerExchange: 2.0 },
    { name: "Cowpea (Chavli)", gramsPerExchange: 2.0 },
    { name: "Field bean white (Pavte)", gramsPerExchange: 2.0 },
    { name: "Peas dry (Vatane)", gramsPerExchange: 2.1 },
    { name: "Horsegram (Kulith)", gramsPerExchange: 2.2 },
    { name: "Adzuki beans", gramsPerExchange: 2.0 },
    { name: "Adzuki beans boiled", gramsPerExchange: 5.2 },
    { name: "Beans kidney sprouted", gramsPerExchange: 9.3 },
    { name: "Beans kidney sprouted cooked", gramsPerExchange: 8.1 },
    { name: "Beans pinto sprouted", gramsPerExchange: 7.4 },
    { name: "Beans pinto sprouted boiled", gramsPerExchange: 21.1 },
    { name: "Beans white", gramsPerExchange: 1.6 },
    { name: "Beans white boiled", gramsPerExchange: 3.9 },
    { name: "Beans white small", gramsPerExchange: 1.8 },
    { name: "Beans white small boiled", gramsPerExchange: 4.3 },
    { name: "Beans yellow", gramsPerExchange: 1.7 },
    { name: "Beans yellow boiled", gramsPerExchange: 4.2 },
    { name: "Black beans", gramsPerExchange: 1.8 },
    { name: "Black beans boiled", gramsPerExchange: 4.7 },
    { name: "Black gram dal (Urad dal)", gramsPerExchange: 1.9 },
    { name: "Cowpea brown", gramsPerExchange: 2.0 },
    { name: "Cowpea white", gramsPerExchange: 1.8 },
    { name: "Cranberry beans (Chitriwale rajmah)", gramsPerExchange: 1.7 },
    { name: "Cranberry beans boiled", gramsPerExchange: 4.1 },
    { name: "Field bean black (Val kale)", gramsPerExchange: 1.9 },
    { name: "Field bean brown (Val kadwe)", gramsPerExchange: 1.9 },
    { name: "French beans mature seeds", gramsPerExchange: 2.0 },
    { name: "French beans mature seeds boiled", gramsPerExchange: 5.4 },
    { name: "Great northern beans", gramsPerExchange: 1.7 },
    { name: "Great northern beans boiled", gramsPerExchange: 4.6 },
    { name: "Green gram sprouts boiled", gramsPerExchange: 20.6 },
    { name: "Lentil whole yellowish", gramsPerExchange: 1.8 },
    { name: "Lentil sprouts", gramsPerExchange: 5.0 },
    { name: "Lentil sprouts boiled", gramsPerExchange: 5.1 },
    { name: "Lupins seeds", gramsPerExchange: 1.3 },
    { name: "Lupins seeds boiled", gramsPerExchange: 3.1 },
    { name: "Navy beans", gramsPerExchange: 1.6 },
    { name: "Navy beans boiled", gramsPerExchange: 4.0 },
    { name: "Navy bean sprouts", gramsPerExchange: 6.3 },
    { name: "Navy bean sprouts boiled", gramsPerExchange: 5.5 },
    { name: "Peas green split", gramsPerExchange: 1.7 },
    { name: "Peas mature sprouts", gramsPerExchange: 9.1 },
    { name: "Peas mature sprouts boiled", gramsPerExchange: 7.0 },
    { name: "Pink beans", gramsPerExchange: 1.8 },
    { name: "Pink beans boiled", gramsPerExchange: 4.2 },
    { name: "Pinto beans", gramsPerExchange: 2.0 },
    { name: "Pinto beans boiled", gramsPerExchange: 3.9 },
    { name: "Rajmah black", gramsPerExchange: 2.2 },
    { name: "Rajmah brown", gramsPerExchange: 2.0 },
    { name: "Ricebean (Math)", gramsPerExchange: 1.9 },
    { name: "Soya bean brown", gramsPerExchange: 1.1 },
    { name: "Soya bean white", gramsPerExchange: 1.0 },
    { name: "Soybean sprouts", gramsPerExchange: 3.2 },
    { name: "Soybean sprouts boiled", gramsPerExchange: 5.0 },
    { name: "Yardlong beans seeds", gramsPerExchange: 1.7 },
    { name: "Yardlong beans seeds boiled", gramsPerExchange: 5.1 },
  ],

  "other vegetables": [
    { name: "Brinjal (Vangi)", gramsPerExchange: 29.4 },
    { name: "Bottle gourd (Dudhi)", gramsPerExchange: 58.5 },
    { name: "Bitter gourd (Karle)", gramsPerExchange: 20.0 },
    { name: "Ladies finger (Bhendi/Okra)", gramsPerExchange: 21.6 },
    { name: "Cauliflower (Phulavar)", gramsPerExchange: 16.0 },
    { name: "Capsicum green (Simla mirchi)", gramsPerExchange: 34.9 },
    { name: "Capsicum red", gramsPerExchange: 26.3 },
    { name: "Cucumber (Kakdi)", gramsPerExchange: 46.3 },
    { name: "French beans (Farsabi)", gramsPerExchange: 14.9 },
    { name: "Pumpkin (Bhopla/Lal bhopla)", gramsPerExchange: 39.0 },
    { name: "Tomato ripe (Tamato)", gramsPerExchange: 68.2 },
    { name: "Ridge gourd (Dodka/Shiral)", gramsPerExchange: 36.9 },
    { name: "Drumstick (Shevgyachya shenga)", gramsPerExchange: 15.2 },
    { name: "Cluster beans (Gavar)", gramsPerExchange: 14.2 },
    { name: "Snake gourd (Padval)", gramsPerExchange: 42.6 },
    { name: "Zucchini green", gramsPerExchange: 31.0 },
    { name: "Mushroom button", gramsPerExchange: 9.9 },
    { name: "Broccoli", gramsPerExchange: 16.0 },
    { name: "Tinda (Dhemse)", gramsPerExchange: 33.9 },
    { name: "Ash gourd (Kohla/Petha)", gramsPerExchange: 49.5 },
    { name: "Peas fresh (Matar)", gramsPerExchange: 6.5 },
    { name: "Raw papaya (Kachchi papai)", gramsPerExchange: 126.6 },
    { name: "Raw mango (Kairi)", gramsPerExchange: 50.1 },
    { name: "Parwar (Parval)", gramsPerExchange: 24.0 },
    { name: "Tondli (Kovai)", gramsPerExchange: 29.0 },
    { name: "Spinach (Palak)", gramsPerExchange: 16.0 },
    { name: "Cabbage (Kobi)", gramsPerExchange: 47.6 },
    { name: "Fenugreek leaves (Methi)", gramsPerExchange: 8.7 },
    { name: "Coriander leaves (Kothimbir)", gramsPerExchange: 8.8 },
    { name: "Colocasia leaves (Aluchi pane)", gramsPerExchange: 12.6 },
    { name: "Amaranth leaves (Math bhaji)", gramsPerExchange: 12.1 },
    { name: "Curry leaves (Kadhipatta)", gramsPerExchange: 6.9 },
    { name: "Dill leaves (Shepu)", gramsPerExchange: 13.0 },
    { name: "Bamboo shoot tender", gramsPerExchange: 40.8 },
    { name: "Bean scarlet tender (Chavli shenga)", gramsPerExchange: 15.4 },
    { name: "Bean snap yellow raw", gramsPerExchange: 22.2 },
    { name: "Bottle gourd elongate pale green", gramsPerExchange: 57.3 },
    { name: "Bottle gourd round pale green", gramsPerExchange: 71.7 },
    { name: "Broad beans (Ghevda)", gramsPerExchange: 9.6 },
    { name: "Broad beans immature seeds boiled", gramsPerExchange: 8.5 },
    { name: "Broad beans immature seeds raw", gramsPerExchange: 7.3 },
    { name: "Broccoli flower", gramsPerExchange: 15.6 },
    { name: "Capsicum yellow", gramsPerExchange: 28.3 },
    { name: "Celery stalk", gramsPerExchange: 44.0 },
    { name: "Chili red fresh", gramsPerExchange: 23.8 },
    { name: "Cho-cho marrow", gramsPerExchange: 45.2 },
    { name: "Colocasia stem black (Alu dande)", gramsPerExchange: 44.2 },
    { name: "Colocasia stem green (Alu dande)", gramsPerExchange: 36.9 },
    { name: "Corn baby", gramsPerExchange: 15.3 },
    { name: "Cowpea immature seeds (Chavli dane)", gramsPerExchange: 11.7 },
    { name: "Cucumber orange round", gramsPerExchange: 33.3 },
    { name: "Field beans immature seeds raw (Wal)", gramsPerExchange: 12.9 },
    { name: "Field beans immature seeds boiled (Wal)", gramsPerExchange: 9.2 },
    { name: "Field beans tender broad (Ghevda)", gramsPerExchange: 12.8 },
    { name: "Field beans tender lean (Ghevda)", gramsPerExchange: 10.3 },
    { name: "French beans hybrid (Farsabi)", gramsPerExchange: 15.8 },
    { name: "Jackfruit raw (Kachcha phanas)", gramsPerExchange: 17.9 },
    { name: "Jackfruit seed mature (Athalya)", gramsPerExchange: 5.0 },
    { name: "Knol-Khol (Navalkol)", gramsPerExchange: 23.8 },
    { name: "Kovai small (Tondli chote)", gramsPerExchange: 32.5 },
    { name: "Lima beans immature seeds", gramsPerExchange: 4.7 },
    { name: "Lima beans immature seeds boiled", gramsPerExchange: 4.7 },
    { name: "Maize tender local (Pand maka)", gramsPerExchange: 15.8 },
    { name: "Maize tender sweet (Pivla maka)", gramsPerExchange: 12.4 },
    { name: "Mushroom brown", gramsPerExchange: 17.4 },
    { name: "Mushroom chicken fresh", gramsPerExchange: 20.3 },
    { name: "Mushroom oyster dried", gramsPerExchange: 1.7 },
    { name: "Mushroom shiitake fresh", gramsPerExchange: 10.3 },
    { name: "Peas green boiled", gramsPerExchange: 8.6 },
    { name: "Peas green frozen", gramsPerExchange: 8.8 },
    { name: "Pepper jalapeno raw (Bhaji chi mirchi)", gramsPerExchange: 35.1 },
    { name: "Plantain flower (Kelphul)", gramsPerExchange: 28.6 },
    { name: "Plantain stem (Kelichi khunt)", gramsPerExchange: 97.8 },
    { name: "Pumpkin green cylindrical", gramsPerExchange: 38.5 },
    { name: "Pumpkin orange round", gramsPerExchange: 39.4 },
    { name: "Red gram tender fresh (Turichi shenga)", gramsPerExchange: 5.7 },
    { name: "Ridge gourd smooth (Dodka)", gramsPerExchange: 34.1 },
    { name: "Snake gourd long pale green (Padwal)", gramsPerExchange: 36.1 },
    { name: "Snake gourd short (Padwal)", gramsPerExchange: 68.6 },
    { name: "Snow pea edible podded raw", gramsPerExchange: 7.3 },
    { name: "Soybeans green", gramsPerExchange: 3.5 },
    { name: "Squash summer (Ghosale)", gramsPerExchange: 37.7 },
    { name: "Squash winter (Ghosale)", gramsPerExchange: 32.3 },
    { name: "Tomato orange", gramsPerExchange: 66.7 },
    { name: "Tomato yellow", gramsPerExchange: 80.0 },
    { name: "Tomato green", gramsPerExchange: 57.8 },
    { name: "Tomato ripe hybrid", gramsPerExchange: 96.0 },
    { name: "Turnip (Salgam)", gramsPerExchange: 66.7 },
    { name: "Yardlong beans dark green (Chavli shenga)", gramsPerExchange: 12.3 },
    { name: "Zucchini yellow", gramsPerExchange: 26.7 },
  ],

  "leafy vegetables": [
    { name: "Agathi leaves", gramsPerExchange: 4.2 },
    { name: "Amaranth leaves red (Math bhaji lal)", gramsPerExchange: 9.7 },
    { name: "Amaranth leaves red and green mix", gramsPerExchange: 13.0 },
    { name: "Amaranth spinosus leaves green (Katewala math)", gramsPerExchange: 13.5 },
    { name: "Amaranth spinosus leaves red and green mix", gramsPerExchange: 17.3 },
    { name: "Asparagus raw (Shatavari)", gramsPerExchange: 17.4 },
    { name: "Asparagus cooked (Shatavari)", gramsPerExchange: 16.0 },
    { name: "Basella leaves (Mayalu)", gramsPerExchange: 32.8 },
    { name: "Bathua leaves (Chakwat)", gramsPerExchange: 13.2 },
    { name: "Beet greens (Bitachi pane)", gramsPerExchange: 19.7 },
    { name: "Betel leaves big Kolkata (Vida paan)", gramsPerExchange: 23.0 },
    { name: "Betel leaves small (Vida paan)", gramsPerExchange: 19.4 },
    { name: "Brussels sprout", gramsPerExchange: 9.9 },
    { name: "Cabbage collard greens", gramsPerExchange: 9.8 },
    { name: "Cabbage chinese", gramsPerExchange: 30.3 },
    { name: "Cabbage chinese pe-tsai raw", gramsPerExchange: 37.7 },
    { name: "Cabbage green (Hirva kobi)", gramsPerExchange: 30.4 },
    { name: "Cabbage violet (Lal kobi)", gramsPerExchange: 26.3 },
    { name: "Cauliflower leaves", gramsPerExchange: 10.4 },
    { name: "Celery leaves (Selari)", gramsPerExchange: 74.1 },
    { name: "Chard swiss (Silver beet)", gramsPerExchange: 18.2 },
    { name: "Chard swiss boiled", gramsPerExchange: 17.5 },
    { name: "Chives raw", gramsPerExchange: 13.8 },
    { name: "Drumstick leaves (Shevgyacha pala)", gramsPerExchange: 7.1 },
    { name: "Knol-Khol leaves (Navalkol pane)", gramsPerExchange: 11.2 },
    { name: "Leeks raw", gramsPerExchange: 35.7 },
    { name: "Leeks boiled", gramsPerExchange: 64.5 },
    { name: "Lettuce green leaf", gramsPerExchange: 28.6 },
    { name: "Lettuce iceberg", gramsPerExchange: 83.3 },
    { name: "Lettuce red leaf", gramsPerExchange: 41.7 },
    { name: "Lettuce romaine", gramsPerExchange: 36.4 },
    { name: "Mint leaves (Pudina)", gramsPerExchange: 7.5 },
    { name: "Mustard leaves (Mohri pane)", gramsPerExchange: 16.1 },
    { name: "Onion stalk (Kandyachya pati)", gramsPerExchange: 16.4 },
    { name: "Pak Choi leaves", gramsPerExchange: 25.0 },
    { name: "Parsley (English kothimbir)", gramsPerExchange: 5.8 },
    { name: "Ponnaganni", gramsPerExchange: 6.4 },
    { name: "Pumpkin leaves tender (Bhoplya pane)", gramsPerExchange: 8.2 },
    { name: "Radish leaves (Mulyachi pane)", gramsPerExchange: 21.1 },
    { name: "Rumex leaves (Ambada)", gramsPerExchange: 31.1 },
    { name: "Seaweed spirulina", gramsPerExchange: 5.5 },
    { name: "Spring onions top and bulb", gramsPerExchange: 24.7 },
    { name: "Tamarind leaves tender (Chinchecha pala)", gramsPerExchange: 6.1 },
    { name: "Turnip greens (Salgam chi pane)", gramsPerExchange: 19.6 },
    { name: "Turnip greens boiled", gramsPerExchange: 25.6 },
    { name: "Watercress (Aliv bhaji)", gramsPerExchange: 14.6 },
  ],

  "root vegetables": [
    { name: "Potato (Batata)", gramsPerExchange: 30.3 },
    { name: "Potato boiled", gramsPerExchange: 20.0 },
    { name: "Carrot (Gajar)", gramsPerExchange: 46.0 },
    { name: "Beet root (Bit)", gramsPerExchange: 18.3 },
    { name: "Onion big (Kanda)", gramsPerExchange: 48.5 },
    { name: "Onion small (Shallots)", gramsPerExchange: 28.0 },
    { name: "Sweet potato (Ratale)", gramsPerExchange: 27.0 },
    { name: "Colocasia (Alkudi/Arabi)", gramsPerExchange: 11.3 },
    { name: "Radish white (Mula)", gramsPerExchange: 46.6 },
    { name: "Plantain green (Kachche kele)", gramsPerExchange: 30.8 },
    { name: "Yam (Suran)", gramsPerExchange: 19.9 },
    { name: "Tapioca (Simla batata)", gramsPerExchange: 41.1 },
    { name: "Lotus root (Kamal kakdi)", gramsPerExchange: 22.6 },
    { name: "Casava", gramsPerExchange: 57.1 },
    { name: "Carrot red (Gajar lal)", gramsPerExchange: 43.0 },
    { name: "Carrots baby raw", gramsPerExchange: 55.6 },
    { name: "Onion sweet (Safed kanda)", gramsPerExchange: 100.0 },
    { name: "Potato boiled with skin", gramsPerExchange: 19.0 },
    { name: "Potato boiled without skin", gramsPerExchange: 20.8 },
    { name: "Potato brown skin small", gramsPerExchange: 35.0 },
    { name: "Potato red skin", gramsPerExchange: 33.5 },
    { name: "Radish elongate red skin (Mula lal)", gramsPerExchange: 58.0 },
    { name: "Radish round red skin", gramsPerExchange: 42.6 },
    { name: "Radish round white skin", gramsPerExchange: 48.3 },
    { name: "Shallots small (Chote kande)", gramsPerExchange: 18.2 },
    { name: "Sweet potato pink skin (Ratale gulabi)", gramsPerExchange: 27.5 },
    { name: "Water chestnut (Shingada)", gramsPerExchange: 61.2 },
    { name: "Yam elephant (Suran)", gramsPerExchange: 13.4 },
    { name: "Yam wild (Suran ran)", gramsPerExchange: 10.9 },
  ],

  "free group": [
    { name: "Sago / Arrowroot (Sabudana)", gramsPerExchange: 14 },
    { name: "Corn Starch (Cornflour)", gramsPerExchange: 13 },
    { name: "Wheat Starch", gramsPerExchange: 14 },
    { name: "Maize Corn Starch", gramsPerExchange: 14 },
    { name: "Mixed Fruit Jam", gramsPerExchange: 18 },
    { name: "Molasses", gramsPerExchange: 17 },
    { name: "Custard Powder", gramsPerExchange: 13 },
    { name: "Corn Syrup (Light)", gramsPerExchange: 18 },
    { name: "Rice Milk", gramsPerExchange: 105, unit: "ml" },
    { name: "Aam Papad", gramsPerExchange: 16 },
    { name: "Gulkand", gramsPerExchange: 18 },
    { name: "Ice cream (Creambell)", gramsPerExchange: 41 },
    { name: "Mapro Mixed Fruit Jam", gramsPerExchange: 19 },
    { name: "Patanjali Mixed Fruit Jam", gramsPerExchange: 17 },
    { name: "Potato Starch", gramsPerExchange: 15 },
    { name: "Corn Syrup Dark", gramsPerExchange: 17, unit: "ml" },
    { name: "Wikfield Cornflour", gramsPerExchange: 14 },
  ],

  miscellaneous: [
    { name: "Mango ginger (Ambehalad)", gramsPerExchange: 7.2 },
    { name: "Jaggery cane (Gul)", gramsPerExchange: 7.8 },
    { name: "Coconut milk (Nariyal doodh)", gramsPerExchange: 3.6 },
    { name: "Coconut water (Naral pani)", gramsPerExchange: 63.7 },
    { name: "Coconut kernel dry (Suka khobra)", gramsPerExchange: 1.4 },
    { name: "Coconut kernel fresh (Ola khobra)", gramsPerExchange: 2.2 },
    { name: "Tomato juice canned", gramsPerExchange: 29.4 },
    { name: "Tomato paste without salt", gramsPerExchange: 5.7 },
    { name: "Tomato puree", gramsPerExchange: 15.2 },
    { name: "Tomato sauce", gramsPerExchange: 18.5 },
    { name: "Butter (Loni)", gramsPerExchange: 8.8 },
  ],

  candies: [
    { name: "4 Fruits Pudding Jelly", gramsPerExchange: 63 },
    { name: "Ahmed Jelly Crystal Lychee Jelly", gramsPerExchange: 14 },
    { name: "Alpenliebe Jutz Jelly Fruity Bars", gramsPerExchange: 16 },
    { name: "Alpenliebe Mangofillz", gramsPerExchange: 13 },
    { name: "Alpenliebe Pop", gramsPerExchange: 12 },
    { name: "Brookside dark exotic chocolate", gramsPerExchange: 11 },
    { name: "Candies Butterscotch", gramsPerExchange: 13 },
    { name: "Candies Gumdrops (Starch Jelly)", gramsPerExchange: 13 },
    { name: "Candies Hard", gramsPerExchange: 13 },
    { name: "Candies Jelly Beans", gramsPerExchange: 13 },
    { name: "Candyman Jellicious Jelimals", gramsPerExchange: 15 },
    { name: "Candyman Jellicious With Real Strawberry Pulp", gramsPerExchange: 15 },
    { name: "Chewing Gum", gramsPerExchange: 14 },
    { name: "Confeito Chocolate Vermicelli", gramsPerExchange: 50 },
    { name: "Confeito Rainbow Vermicelli", gramsPerExchange: 50 },
    { name: "Crush Pop (Lolipop) Mix Fruit", gramsPerExchange: 13 },
    { name: "Darling Velvetto", gramsPerExchange: 13 },
    { name: "Falchoos", gramsPerExchange: 17 },
    { name: "Falero (Jamun)", gramsPerExchange: 17 },
    { name: "Falero (Kacchi Kairy)", gramsPerExchange: 17 },
    { name: "Falero (Strawberry)", gramsPerExchange: 18 },
    { name: "Falero Pineapple", gramsPerExchange: 17 },
    { name: "Falero Wahwah Guava", gramsPerExchange: 17 },
    { name: "Fox Crystal Clear", gramsPerExchange: 16 },
    { name: "Fru Asorted Pack", gramsPerExchange: 16 },
    { name: "Frubbles Fruit Pebbles Purple Colour", gramsPerExchange: 16 },
    { name: "Frubbles Fruit Pebbles Yellow Colour", gramsPerExchange: 16 },
    { name: "Galaxy Real Jelly Sweets", gramsPerExchange: 17 },
    { name: "Geeef Magic Pops", gramsPerExchange: 14 },
    { name: "Glucovita Bolts Orange", gramsPerExchange: 14 },
    { name: "Gula Gula", gramsPerExchange: 15 },
    { name: "Harmik Phantom Sweet Cigarette Candy", gramsPerExchange: 13 },
    { name: "Jellies", gramsPerExchange: 19 },
    { name: "Jolly Rancher Chews Mixed Fruit", gramsPerExchange: 13 },
    { name: "Jolly Rancher Hard Candy", gramsPerExchange: 13 },
    { name: "Jolly Rancher Lollipops", gramsPerExchange: 13 },
    { name: "Just Jelly (Guava)", gramsPerExchange: 16 },
    { name: "Just Jelly (Kacchi Kairy)", gramsPerExchange: 16 },
    { name: "Just Jelly (Litchi)", gramsPerExchange: 16 },
    { name: "Just Jelly (Strawberry)", gramsPerExchange: 16 },
    { name: "Justjelly Fruity Bear", gramsPerExchange: 16 },
    { name: "Luvit Crazy Maker Lolipop Fruit Flavour", gramsPerExchange: 13 },
    { name: "Mala's Froogle Fruity Chews", gramsPerExchange: 14 },
    { name: "Mala's Butter Scotch Apple", gramsPerExchange: 19 },
    { name: "Mala's Melties Lichi", gramsPerExchange: 49 },
    { name: "Mala's Melties Mango", gramsPerExchange: 49 },
    { name: "Mapro Falchoos", gramsPerExchange: 17 },
    { name: "Mapro Fruity Sweet", gramsPerExchange: 17 },
    { name: "Mazelo Flavour Candy", gramsPerExchange: 13 },
    { name: "Mentos", gramsPerExchange: 14 },
    { name: "Nilons Fruits (Tooty Fruity)", gramsPerExchange: 17 },
    { name: "Parle Fruit Jelly Mixed", gramsPerExchange: 15 },
    { name: "Parle Kaccha Mango Bite", gramsPerExchange: 13 },
    { name: "Passpass Pulse Guava With Tangy Twist", gramsPerExchange: 13 },
    { name: "Passpass Pulse Kachcha Aam With Tangy Twist", gramsPerExchange: 13 },
    { name: "Tic Tac", gramsPerExchange: 13 },
  ],

  juices: [
    { name: "Active Fiber+", gramsPerExchange: 94, unit: "ml" },
    { name: "B Natural Guava", gramsPerExchange: 83, unit: "ml" },
    { name: "B Natural Lichi", gramsPerExchange: 91, unit: "ml" },
    { name: "B Natural Orange", gramsPerExchange: 89, unit: "ml" },
    { name: "B Natural Pineapple", gramsPerExchange: 88, unit: "ml" },
    { name: "Del Monte Green Apple", gramsPerExchange: 110, unit: "ml" },
    { name: "Del Monte Mango", gramsPerExchange: 81, unit: "ml" },
    { name: "Del Monte Pineapple", gramsPerExchange: 94, unit: "ml" },
    { name: "Delmonte Four Season Mixed Fruit", gramsPerExchange: 98, unit: "ml" },
    { name: "Euro Fresho Mango Juice", gramsPerExchange: 77, unit: "ml" },
    { name: "Euro Fresho Litchi", gramsPerExchange: 89, unit: "ml" },
    { name: "Euro Fresho Mango Pulp", gramsPerExchange: 77, unit: "ml" },
    { name: "Frooti Mango Drink", gramsPerExchange: 77 },
    { name: "Hershey's Syrup Strawberry", gramsPerExchange: 18, unit: "ml" },
    { name: "KISSAN Lemon Squash", gramsPerExchange: 25, unit: "ml" },
    { name: "Kissan Mango Squash", gramsPerExchange: 23, unit: "ml" },
    { name: "Lichika Lichi Drink", gramsPerExchange: 86, unit: "ml" },
    { name: "Mala's Lichi Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mala's Mango Squash", gramsPerExchange: 27, unit: "ml" },
    { name: "Mala's Strawberry Crush", gramsPerExchange: 20, unit: "ml" },
    { name: "Mala's Pineapple Crush", gramsPerExchange: 22, unit: "ml" },
    { name: "Mala's Green Apple Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mala's Banana Crush", gramsPerExchange: 17, unit: "ml" },
    { name: "Maple Syrup", gramsPerExchange: 19, unit: "ml" },
    { name: "Mapro Rose Sharbat", gramsPerExchange: 14, unit: "ml" },
    { name: "Mapro Mango Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Litchi Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Kiwi Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Green Apple Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Mapro Pinacolada Squash", gramsPerExchange: 16, unit: "ml" },
    { name: "Marmalade Orange", gramsPerExchange: 20 },
    { name: "Maza Gold Tetra Pack", gramsPerExchange: 89, unit: "ml" },
    { name: "Mazza Mango", gramsPerExchange: 93, unit: "ml" },
    { name: "Minute Maid Mosambi", gramsPerExchange: 104, unit: "ml" },
    { name: "Minute Maid Mango", gramsPerExchange: 78, unit: "ml" },
    { name: "Minute Maid Mixed Fruit", gramsPerExchange: 89, unit: "ml" },
    { name: "Mrs. Food Rite Rose Sharbat", gramsPerExchange: 14, unit: "ml" },
    { name: "Mushy Mango Rush (CCD)", gramsPerExchange: 89, unit: "ml" },
    { name: "Paper Boat Jaljeera", gramsPerExchange: 109, unit: "ml" },
    { name: "Paper Boat Guava", gramsPerExchange: 105, unit: "ml" },
    { name: "Paper Boat Mixed Fruit", gramsPerExchange: 105, unit: "ml" },
    { name: "Paper Boat Aampanna", gramsPerExchange: 104, unit: "ml" },
    { name: "Paper Boat Anar", gramsPerExchange: 106, unit: "ml" },
    { name: "Patanjali Guava", gramsPerExchange: 80, unit: "ml" },
    { name: "Patanjali Mango", gramsPerExchange: 77, unit: "ml" },
    { name: "Pran Litchi Drink", gramsPerExchange: 96, unit: "ml" },
    { name: "Rasna Apple", gramsPerExchange: 13 },
    { name: "Rasna Mango", gramsPerExchange: 13 },
    { name: "Rasna Nimbupani", gramsPerExchange: 13 },
    { name: "Rasna Orange", gramsPerExchange: 13 },
    { name: "Real Apple", gramsPerExchange: 83, unit: "ml" },
    { name: "Real Lichi", gramsPerExchange: 83, unit: "ml" },
    { name: "Real Mango", gramsPerExchange: 82, unit: "ml" },
    { name: "Real Orange", gramsPerExchange: 89, unit: "ml" },
    { name: "Real Active Fiber+", gramsPerExchange: 94, unit: "ml" },
    { name: "Real Pineapple", gramsPerExchange: 89, unit: "ml" },
    { name: "Real Pomegranate", gramsPerExchange: 83, unit: "ml" },
    { name: "Syrup Fruit", gramsPerExchange: 15, unit: "ml" },
    { name: "Syrup Nestle Chocolate", gramsPerExchange: 19, unit: "ml" },
    { name: "Tang Mango", gramsPerExchange: 13 },
    { name: "Tang Nimbupani", gramsPerExchange: 13 },
    { name: "Tang Orange", gramsPerExchange: 13 },
    { name: "Tropicana Apple", gramsPerExchange: 104, unit: "ml" },
    { name: "Tropicana Essentials Fruit & Veggies", gramsPerExchange: 106, unit: "ml" },
    { name: "Tropicana Lichi", gramsPerExchange: 86, unit: "ml" },
    { name: "Tropicana Mango", gramsPerExchange: 82, unit: "ml" },
    { name: "Tropicana Orange", gramsPerExchange: 96, unit: "ml" },
    { name: "Tropicana Pomegranate", gramsPerExchange: 89, unit: "ml" },
    { name: "Tropicana Slice Juice", gramsPerExchange: 76, unit: "ml" },
    { name: "Tropicana Pineapple", gramsPerExchange: 93, unit: "ml" },
    { name: "Guruji's Orange Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Manama Mango Crush", gramsPerExchange: 20 },
    { name: "Macro Alphonso Mango Crush", gramsPerExchange: 18, unit: "ml" },
    { name: "Alo Fruit Berries", gramsPerExchange: 86, unit: "ml" },
    { name: "Coffee Day Mushy Mango", gramsPerExchange: 89, unit: "ml" },
    { name: "Jeeru Jeera Masala", gramsPerExchange: 114, unit: "ml" },
    { name: "Cravova Peach Majito", gramsPerExchange: 89, unit: "ml" },
    { name: "Baskin Robbins Raspberry Sorbet small scoop", gramsPerExchange: 56, unit: "ml" },
  ],

  "sugar coated dried fruits": [
    { name: "Cranberries dried sweetened", gramsPerExchange: 16 },
    { name: "Flyberry dehydrated pineapple", gramsPerExchange: 15 },
    { name: "Flyberry raspberry", gramsPerExchange: 15 },
    { name: "Gourima amla candy", gramsPerExchange: 15 },
    { name: "Gourima dried kiwis", gramsPerExchange: 14 },
    { name: "Gourima fruit mix", gramsPerExchange: 14 },
    { name: "Happilo dried mango", gramsPerExchange: 13 },
    { name: "Nourish amla candy", gramsPerExchange: 15 },
    { name: "Nourish cranberry candy", gramsPerExchange: 14 },
    { name: "Nourish guava candy", gramsPerExchange: 13 },
    { name: "Nourish mango candy", gramsPerExchange: 14 },
    { name: "Nourish mixed fruits", gramsPerExchange: 14 },
    { name: "Nourish pineapple candy", gramsPerExchange: 13 },
    { name: "Nutriplato fruit chunks", gramsPerExchange: 14 },
    { name: "Regency dried cranberries slice", gramsPerExchange: 14 },
    { name: "Regency dried cranberries whole", gramsPerExchange: 14 },
    { name: "Welch's fruit snacks", gramsPerExchange: 16 },
  ],

  "mayo and cheese": [
    { name: "So Good Almond Vanilla Milk", gramsPerExchange: 50, unit: "ml" },
    { name: "So Good Almond Chocolate Milk", gramsPerExchange: 38, unit: "ml" },
    { name: "Dabar Homemade Coconut Milk", gramsPerExchange: 35, unit: "ml" },
    { name: "Urban Platter Vegan Cheeze Sauce Mix", gramsPerExchange: 50 },
    { name: "World's First Vegan Jalapeno Cheese Dip", gramsPerExchange: 36 },
    { name: "Urban Platter Vegan Premium Mayo", gramsPerExchange: 30 },
    { name: "Bombay Cheese Company Cheddar", gramsPerExchange: 50 },
    { name: "Violife Mature Cheddar Slice", gramsPerExchange: 50 },
    { name: "Surabhi Mayonnaise", gramsPerExchange: 88 },
    { name: "Sheeze Grated Mozzerlla Style", gramsPerExchange: 300 },
    { name: "Grated Sheese Veg Mature Cheddar Style", gramsPerExchange: 43 },
    { name: "Hellmanns Light Mayo", gramsPerExchange: 60 },
  ],
};
